// Generated by <a href="http://scalaxb.org/">scalaxb</a>.
package eveapi.xml.eve.FacWarTopStats

case class Eveapi(currentTime: String,
                  result: eveapi.xml.eve.FacWarTopStats.Result,
                  cachedUntil: String,
                  attributes: Map[String, scalaxb.DataRecord[Any]] = Map()) {
  lazy val version = attributes("@version").as[BigInt]
}

case class Result(characters: eveapi.xml.eve.FacWarTopStats.Characters,
                  corporations: eveapi.xml.eve.FacWarTopStats.Corporations,
                  factions: eveapi.xml.eve.FacWarTopStats.Factions)

case class Characters(rowset: eveapi.xml.eve.FacWarTopStats.Rowset*)

case class Corporations(rowset: eveapi.xml.eve.FacWarTopStats.Rowset*)

case class Factions(rowset: eveapi.xml.eve.FacWarTopStats.Rowset*)

case class Rowset(row: Seq[eveapi.xml.eve.FacWarTopStats.Row] = Nil,
                  attributes: Map[String, scalaxb.DataRecord[Any]] = Map()) {
  lazy val columns = attributes("@columns").as[String]
  lazy val key = attributes("@key").as[String]
  lazy val name = attributes("@name").as[String]
}

case class Row(attributes: Map[String, scalaxb.DataRecord[Any]] = Map()) {
  lazy val characterID = attributes.get("@characterID") map { _.as[BigInt] }
  lazy val characterName = attributes.get("@characterName") map { _.as[String] }
  lazy val corporationID = attributes.get("@corporationID") map { _.as[BigInt] }
  lazy val corporationName = attributes.get("@corporationName") map { _.as[String] }
  lazy val factionID = attributes.get("@factionID") map { _.as[BigInt] }
  lazy val factionName = attributes.get("@factionName") map { _.as[String] }
  lazy val kills = attributes.get("@kills") map { _.as[BigInt] }
  lazy val victoryPoints = attributes.get("@victoryPoints") map { _.as[BigInt] }
}
