// Generated by <a href="http://scalaxb.org/">scalaxb</a>.
package eveapi.xml.eve.FacWarTopStats

import scala.concurrent.Future


/**
usage:
val obj = scalaxb.fromXML[eveapi.xml.eve.FacWarTopStats.Foo](node)
val document = scalaxb.toXML[eveapi.xml.eve.FacWarTopStats.Foo](obj, "foo", eveapi.xml.eve.FacWarTopStats.defaultScope)
**/
object `package` extends XMLProtocol { }

trait XMLProtocol extends scalaxb.XMLStandardTypes {
  implicit lazy val executionContext = scala.concurrent.ExecutionContext.Implicits.global

  val defaultScope = scalaxb.toScope(Some("xs") -> "http://www.w3.org/2001/XMLSchema",
    Some("xsi") -> "http://www.w3.org/2001/XMLSchema-instance")
  implicit lazy val FacWarTopStatsEveapiFormat: scalaxb.XMLFormat[eveapi.xml.eve.FacWarTopStats.Eveapi] = new DefaultFacWarTopStatsEveapiFormat {}
  implicit lazy val FacWarTopStatsResultFormat: scalaxb.XMLFormat[eveapi.xml.eve.FacWarTopStats.Result] = new DefaultFacWarTopStatsResultFormat {}
  implicit lazy val FacWarTopStatsCharactersFormat: scalaxb.XMLFormat[eveapi.xml.eve.FacWarTopStats.Characters] = new DefaultFacWarTopStatsCharactersFormat {}
  implicit lazy val FacWarTopStatsCorporationsFormat: scalaxb.XMLFormat[eveapi.xml.eve.FacWarTopStats.Corporations] = new DefaultFacWarTopStatsCorporationsFormat {}
  implicit lazy val FacWarTopStatsFactionsFormat: scalaxb.XMLFormat[eveapi.xml.eve.FacWarTopStats.Factions] = new DefaultFacWarTopStatsFactionsFormat {}
  implicit lazy val FacWarTopStatsRowsetFormat: scalaxb.XMLFormat[eveapi.xml.eve.FacWarTopStats.Rowset] = new DefaultFacWarTopStatsRowsetFormat {}
  implicit lazy val FacWarTopStatsRowFormat: scalaxb.XMLFormat[eveapi.xml.eve.FacWarTopStats.Row] = new DefaultFacWarTopStatsRowFormat {}

  trait DefaultFacWarTopStatsEveapiFormat extends scalaxb.ElemNameParser[eveapi.xml.eve.FacWarTopStats.Eveapi] {
    val targetNamespace: Option[String] = None
    
    def parser(node: scala.xml.Node, stack: List[scalaxb.ElemName]): Parser[eveapi.xml.eve.FacWarTopStats.Eveapi] =
      phrase((scalaxb.ElemName(None, "currentTime")) ~ 
      (scalaxb.ElemName(None, "result")) ~ 
      (scalaxb.ElemName(None, "cachedUntil")) ^^
      { case p1 ~ p2 ~ p3 =>
      eveapi.xml.eve.FacWarTopStats.Eveapi(scalaxb.fromXML[String](p1, scalaxb.ElemName(node) :: stack),
        scalaxb.fromXML[eveapi.xml.eve.FacWarTopStats.Result](p2, scalaxb.ElemName(node) :: stack),
        scalaxb.fromXML[String](p3, scalaxb.ElemName(node) :: stack),
        scala.collection.immutable.ListMap(List(
        (node \ "@version").headOption map { x => scalaxb.DataRecord(x, node, scalaxb.fromXML[BigInt](x, scalaxb.ElemName(node) :: stack)) } map { "@version" -> _ }
        ).flatten[(String, scalaxb.DataRecord[Any])]: _*)) })
    
    override def writesAttribute(__obj: eveapi.xml.eve.FacWarTopStats.Eveapi, __scope: scala.xml.NamespaceBinding): scala.xml.MetaData = {
      var attr: scala.xml.MetaData  = scala.xml.Null
      __obj.attributes.toList map {
        case ("@version", _) => attr = scala.xml.Attribute(null, "version", __obj.version.toString, attr)
        case (key, x) => attr = scala.xml.Attribute((x.namespace map { __scope.getPrefix(_) }).orNull, x.key.orNull, x.value.toString, attr)
      }
      attr
    }

    def writesChildNodes(__obj: eveapi.xml.eve.FacWarTopStats.Eveapi, __scope: scala.xml.NamespaceBinding): Seq[scala.xml.Node] =
      Seq.concat(scalaxb.toXML[String](__obj.currentTime, None, Some("currentTime"), __scope, false),
        scalaxb.toXML[eveapi.xml.eve.FacWarTopStats.Result](__obj.result, None, Some("result"), __scope, false),
        scalaxb.toXML[String](__obj.cachedUntil, None, Some("cachedUntil"), __scope, false))

  }

  trait DefaultFacWarTopStatsResultFormat extends scalaxb.ElemNameParser[eveapi.xml.eve.FacWarTopStats.Result] {
    val targetNamespace: Option[String] = None
    
    def parser(node: scala.xml.Node, stack: List[scalaxb.ElemName]): Parser[eveapi.xml.eve.FacWarTopStats.Result] =
      phrase((scalaxb.ElemName(None, "characters")) ~ 
      (scalaxb.ElemName(None, "corporations")) ~ 
      (scalaxb.ElemName(None, "factions")) ^^
      { case p1 ~ p2 ~ p3 =>
      eveapi.xml.eve.FacWarTopStats.Result(scalaxb.fromXML[eveapi.xml.eve.FacWarTopStats.Characters](p1, scalaxb.ElemName(node) :: stack),
        scalaxb.fromXML[eveapi.xml.eve.FacWarTopStats.Corporations](p2, scalaxb.ElemName(node) :: stack),
        scalaxb.fromXML[eveapi.xml.eve.FacWarTopStats.Factions](p3, scalaxb.ElemName(node) :: stack)) })
    
    def writesChildNodes(__obj: eveapi.xml.eve.FacWarTopStats.Result, __scope: scala.xml.NamespaceBinding): Seq[scala.xml.Node] =
      Seq.concat(scalaxb.toXML[eveapi.xml.eve.FacWarTopStats.Characters](__obj.characters, None, Some("characters"), __scope, false),
        scalaxb.toXML[eveapi.xml.eve.FacWarTopStats.Corporations](__obj.corporations, None, Some("corporations"), __scope, false),
        scalaxb.toXML[eveapi.xml.eve.FacWarTopStats.Factions](__obj.factions, None, Some("factions"), __scope, false))

  }

  trait DefaultFacWarTopStatsCharactersFormat extends scalaxb.ElemNameParser[eveapi.xml.eve.FacWarTopStats.Characters] {
    val targetNamespace: Option[String] = None
    
    def parser(node: scala.xml.Node, stack: List[scalaxb.ElemName]): Parser[eveapi.xml.eve.FacWarTopStats.Characters] =
      phrase(safeRep(scalaxb.ElemName(None, "rowset")) ^^
      { case p1 =>
      eveapi.xml.eve.FacWarTopStats.Characters(p1.toSeq map { scalaxb.fromXML[eveapi.xml.eve.FacWarTopStats.Rowset](_, scalaxb.ElemName(node) :: stack) }: _*) })
    
    def writesChildNodes(__obj: eveapi.xml.eve.FacWarTopStats.Characters, __scope: scala.xml.NamespaceBinding): Seq[scala.xml.Node] =
      (__obj.rowset flatMap { scalaxb.toXML[eveapi.xml.eve.FacWarTopStats.Rowset](_, None, Some("rowset"), __scope, false) })

  }

  trait DefaultFacWarTopStatsCorporationsFormat extends scalaxb.ElemNameParser[eveapi.xml.eve.FacWarTopStats.Corporations] {
    val targetNamespace: Option[String] = None
    
    def parser(node: scala.xml.Node, stack: List[scalaxb.ElemName]): Parser[eveapi.xml.eve.FacWarTopStats.Corporations] =
      phrase(safeRep(scalaxb.ElemName(None, "rowset")) ^^
      { case p1 =>
      eveapi.xml.eve.FacWarTopStats.Corporations(p1.toSeq map { scalaxb.fromXML[eveapi.xml.eve.FacWarTopStats.Rowset](_, scalaxb.ElemName(node) :: stack) }: _*) })
    
    def writesChildNodes(__obj: eveapi.xml.eve.FacWarTopStats.Corporations, __scope: scala.xml.NamespaceBinding): Seq[scala.xml.Node] =
      (__obj.rowset flatMap { scalaxb.toXML[eveapi.xml.eve.FacWarTopStats.Rowset](_, None, Some("rowset"), __scope, false) })

  }

  trait DefaultFacWarTopStatsFactionsFormat extends scalaxb.ElemNameParser[eveapi.xml.eve.FacWarTopStats.Factions] {
    val targetNamespace: Option[String] = None
    
    def parser(node: scala.xml.Node, stack: List[scalaxb.ElemName]): Parser[eveapi.xml.eve.FacWarTopStats.Factions] =
      phrase(safeRep(scalaxb.ElemName(None, "rowset")) ^^
      { case p1 =>
      eveapi.xml.eve.FacWarTopStats.Factions(p1.toSeq map { scalaxb.fromXML[eveapi.xml.eve.FacWarTopStats.Rowset](_, scalaxb.ElemName(node) :: stack) }: _*) })
    
    def writesChildNodes(__obj: eveapi.xml.eve.FacWarTopStats.Factions, __scope: scala.xml.NamespaceBinding): Seq[scala.xml.Node] =
      (__obj.rowset flatMap { scalaxb.toXML[eveapi.xml.eve.FacWarTopStats.Rowset](_, None, Some("rowset"), __scope, false) })

  }

  trait DefaultFacWarTopStatsRowsetFormat extends scalaxb.ElemNameParser[eveapi.xml.eve.FacWarTopStats.Rowset] {
    val targetNamespace: Option[String] = None
    
    def parser(node: scala.xml.Node, stack: List[scalaxb.ElemName]): Parser[eveapi.xml.eve.FacWarTopStats.Rowset] =
      phrase(safeRep(scalaxb.ElemName(None, "row")) ^^
      { case p1 =>
      eveapi.xml.eve.FacWarTopStats.Rowset(p1.toSeq map { scalaxb.fromXML[eveapi.xml.eve.FacWarTopStats.Row](_, scalaxb.ElemName(node) :: stack) },
        scala.collection.immutable.ListMap(List(
        (node \ "@columns").headOption map { x => scalaxb.DataRecord(x, node, scalaxb.fromXML[String](x, scalaxb.ElemName(node) :: stack)) } map { "@columns" -> _ },
        (node \ "@key").headOption map { x => scalaxb.DataRecord(x, node, scalaxb.fromXML[String](x, scalaxb.ElemName(node) :: stack)) } map { "@key" -> _ },
        (node \ "@name").headOption map { x => scalaxb.DataRecord(x, node, scalaxb.fromXML[String](x, scalaxb.ElemName(node) :: stack)) } map { "@name" -> _ }
        ).flatten[(String, scalaxb.DataRecord[Any])]: _*)) })
    
    override def writesAttribute(__obj: eveapi.xml.eve.FacWarTopStats.Rowset, __scope: scala.xml.NamespaceBinding): scala.xml.MetaData = {
      var attr: scala.xml.MetaData  = scala.xml.Null
      __obj.attributes.toList map {
        case ("@columns", _) => attr = scala.xml.Attribute(null, "columns", __obj.columns.toString, attr)
        case ("@key", _) => attr = scala.xml.Attribute(null, "key", __obj.key.toString, attr)
        case ("@name", _) => attr = scala.xml.Attribute(null, "name", __obj.name.toString, attr)
        case (key, x) => attr = scala.xml.Attribute((x.namespace map { __scope.getPrefix(_) }).orNull, x.key.orNull, x.value.toString, attr)
      }
      attr
    }

    def writesChildNodes(__obj: eveapi.xml.eve.FacWarTopStats.Rowset, __scope: scala.xml.NamespaceBinding): Seq[scala.xml.Node] =
      (__obj.row flatMap { scalaxb.toXML[eveapi.xml.eve.FacWarTopStats.Row](_, None, Some("row"), __scope, false) })

  }

  trait DefaultFacWarTopStatsRowFormat extends scalaxb.XMLFormat[eveapi.xml.eve.FacWarTopStats.Row] with scalaxb.CanWriteChildNodes[eveapi.xml.eve.FacWarTopStats.Row] {
    val targetNamespace: Option[String] = None
    import scalaxb.ElemName._
    
    def reads(seq: scala.xml.NodeSeq, stack: List[scalaxb.ElemName]): Either[String, eveapi.xml.eve.FacWarTopStats.Row] = seq match {
      case node: scala.xml.Node => Right(eveapi.xml.eve.FacWarTopStats.Row(scala.collection.immutable.ListMap(List(
        (node \ "@characterID").headOption map { x => scalaxb.DataRecord(x, node, scalaxb.fromXML[BigInt](x, scalaxb.ElemName(node) :: stack)) } map { "@characterID" -> _ },
        (node \ "@characterName").headOption map { x => scalaxb.DataRecord(x, node, scalaxb.fromXML[String](x, scalaxb.ElemName(node) :: stack)) } map { "@characterName" -> _ },
        (node \ "@corporationID").headOption map { x => scalaxb.DataRecord(x, node, scalaxb.fromXML[BigInt](x, scalaxb.ElemName(node) :: stack)) } map { "@corporationID" -> _ },
        (node \ "@corporationName").headOption map { x => scalaxb.DataRecord(x, node, scalaxb.fromXML[String](x, scalaxb.ElemName(node) :: stack)) } map { "@corporationName" -> _ },
        (node \ "@factionID").headOption map { x => scalaxb.DataRecord(x, node, scalaxb.fromXML[BigInt](x, scalaxb.ElemName(node) :: stack)) } map { "@factionID" -> _ },
        (node \ "@factionName").headOption map { x => scalaxb.DataRecord(x, node, scalaxb.fromXML[String](x, scalaxb.ElemName(node) :: stack)) } map { "@factionName" -> _ },
        (node \ "@kills").headOption map { x => scalaxb.DataRecord(x, node, scalaxb.fromXML[BigInt](x, scalaxb.ElemName(node) :: stack)) } map { "@kills" -> _ },
        (node \ "@victoryPoints").headOption map { x => scalaxb.DataRecord(x, node, scalaxb.fromXML[BigInt](x, scalaxb.ElemName(node) :: stack)) } map { "@victoryPoints" -> _ }
        ).flatten[(String, scalaxb.DataRecord[Any])]: _*)))
      case _ => Left("reads failed: seq must be scala.xml.Node")
    }
    
    override def writesAttribute(__obj: eveapi.xml.eve.FacWarTopStats.Row, __scope: scala.xml.NamespaceBinding): scala.xml.MetaData = {
      var attr: scala.xml.MetaData  = scala.xml.Null
      __obj.attributes.toList map {
        case ("@characterID", _) => __obj.characterID foreach { x => attr = scala.xml.Attribute(null, "characterID", x.toString, attr) }
        case ("@characterName", _) => __obj.characterName foreach { x => attr = scala.xml.Attribute(null, "characterName", x.toString, attr) }
        case ("@corporationID", _) => __obj.corporationID foreach { x => attr = scala.xml.Attribute(null, "corporationID", x.toString, attr) }
        case ("@corporationName", _) => __obj.corporationName foreach { x => attr = scala.xml.Attribute(null, "corporationName", x.toString, attr) }
        case ("@factionID", _) => __obj.factionID foreach { x => attr = scala.xml.Attribute(null, "factionID", x.toString, attr) }
        case ("@factionName", _) => __obj.factionName foreach { x => attr = scala.xml.Attribute(null, "factionName", x.toString, attr) }
        case ("@kills", _) => __obj.kills foreach { x => attr = scala.xml.Attribute(null, "kills", x.toString, attr) }
        case ("@victoryPoints", _) => __obj.victoryPoints foreach { x => attr = scala.xml.Attribute(null, "victoryPoints", x.toString, attr) }
        case (key, x) => attr = scala.xml.Attribute((x.namespace map { __scope.getPrefix(_) }).orNull, x.key.orNull, x.value.toString, attr)
      }
      attr
    }

    def writesChildNodes(__obj: eveapi.xml.eve.FacWarTopStats.Row, __scope: scala.xml.NamespaceBinding): Seq[scala.xml.Node] =
      Nil


  }


}

