// Generated by <a href="http://scalaxb.org/">scalaxb</a>.
package eveapi.xml.server.ServerStatus

case class Eveapi(currentTime: String,
                  result: eveapi.xml.server.ServerStatus.Result,
                  cachedUntil: String,
                  attributes: Map[String, scalaxb.DataRecord[Any]] = Map()) {
  lazy val version = attributes("@version").as[BigInt]
}

case class Result(serverOpen: String, onlinePlayers: BigInt)
