// Generated by <a href="http://scalaxb.org/">scalaxb</a>.
package eveapi.xml.map.Sovereignty

import scala.concurrent.Future


/**
usage:
val obj = scalaxb.fromXML[eveapi.xml.map.Sovereignty.Foo](node)
val document = scalaxb.toXML[eveapi.xml.map.Sovereignty.Foo](obj, "foo", eveapi.xml.map.Sovereignty.defaultScope)
**/
object `package` extends XMLProtocol { }

trait XMLProtocol extends scalaxb.XMLStandardTypes {
  implicit lazy val executionContext = scala.concurrent.ExecutionContext.Implicits.global

  val defaultScope = scalaxb.toScope(Some("xs") -> "http://www.w3.org/2001/XMLSchema",
    Some("xsi") -> "http://www.w3.org/2001/XMLSchema-instance")
  implicit lazy val SovereigntyEveapiFormat: scalaxb.XMLFormat[eveapi.xml.map.Sovereignty.Eveapi] = new DefaultSovereigntyEveapiFormat {}
  implicit lazy val SovereigntyResultFormat: scalaxb.XMLFormat[eveapi.xml.map.Sovereignty.Result] = new DefaultSovereigntyResultFormat {}
  implicit lazy val SovereigntyRowsetFormat: scalaxb.XMLFormat[eveapi.xml.map.Sovereignty.Rowset] = new DefaultSovereigntyRowsetFormat {}
  implicit lazy val SovereigntyRowFormat: scalaxb.XMLFormat[eveapi.xml.map.Sovereignty.Row] = new DefaultSovereigntyRowFormat {}

  trait DefaultSovereigntyEveapiFormat extends scalaxb.ElemNameParser[eveapi.xml.map.Sovereignty.Eveapi] {
    val targetNamespace: Option[String] = None
    
    def parser(node: scala.xml.Node, stack: List[scalaxb.ElemName]): Parser[eveapi.xml.map.Sovereignty.Eveapi] =
      phrase((scalaxb.ElemName(None, "currentTime")) ~ 
      (scalaxb.ElemName(None, "result")) ~ 
      (scalaxb.ElemName(None, "cachedUntil")) ^^
      { case p1 ~ p2 ~ p3 =>
      eveapi.xml.map.Sovereignty.Eveapi(scalaxb.fromXML[String](p1, scalaxb.ElemName(node) :: stack),
        scalaxb.fromXML[eveapi.xml.map.Sovereignty.Result](p2, scalaxb.ElemName(node) :: stack),
        scalaxb.fromXML[String](p3, scalaxb.ElemName(node) :: stack),
        scala.collection.immutable.ListMap(List(
        (node \ "@version").headOption map { x => scalaxb.DataRecord(x, node, scalaxb.fromXML[BigInt](x, scalaxb.ElemName(node) :: stack)) } map { "@version" -> _ }
        ).flatten[(String, scalaxb.DataRecord[Any])]: _*)) })
    
    override def writesAttribute(__obj: eveapi.xml.map.Sovereignty.Eveapi, __scope: scala.xml.NamespaceBinding): scala.xml.MetaData = {
      var attr: scala.xml.MetaData  = scala.xml.Null
      __obj.attributes.toList map {
        case ("@version", _) => attr = scala.xml.Attribute(null, "version", __obj.version.toString, attr)
        case (key, x) => attr = scala.xml.Attribute((x.namespace map { __scope.getPrefix(_) }).orNull, x.key.orNull, x.value.toString, attr)
      }
      attr
    }

    def writesChildNodes(__obj: eveapi.xml.map.Sovereignty.Eveapi, __scope: scala.xml.NamespaceBinding): Seq[scala.xml.Node] =
      Seq.concat(scalaxb.toXML[String](__obj.currentTime, None, Some("currentTime"), __scope, false),
        scalaxb.toXML[eveapi.xml.map.Sovereignty.Result](__obj.result, None, Some("result"), __scope, false),
        scalaxb.toXML[String](__obj.cachedUntil, None, Some("cachedUntil"), __scope, false))

  }

  trait DefaultSovereigntyResultFormat extends scalaxb.ElemNameParser[eveapi.xml.map.Sovereignty.Result] {
    val targetNamespace: Option[String] = None
    
    def parser(node: scala.xml.Node, stack: List[scalaxb.ElemName]): Parser[eveapi.xml.map.Sovereignty.Result] =
      phrase((scalaxb.ElemName(None, "rowset")) ~ 
      (scalaxb.ElemName(None, "dataTime")) ^^
      { case p1 ~ p2 =>
      eveapi.xml.map.Sovereignty.Result(scalaxb.fromXML[eveapi.xml.map.Sovereignty.Rowset](p1, scalaxb.ElemName(node) :: stack),
        scalaxb.fromXML[String](p2, scalaxb.ElemName(node) :: stack)) })
    
    def writesChildNodes(__obj: eveapi.xml.map.Sovereignty.Result, __scope: scala.xml.NamespaceBinding): Seq[scala.xml.Node] =
      Seq.concat(scalaxb.toXML[eveapi.xml.map.Sovereignty.Rowset](__obj.rowset, None, Some("rowset"), __scope, false),
        scalaxb.toXML[String](__obj.dataTime, None, Some("dataTime"), __scope, false))

  }

  trait DefaultSovereigntyRowsetFormat extends scalaxb.ElemNameParser[eveapi.xml.map.Sovereignty.Rowset] {
    val targetNamespace: Option[String] = None
    
    def parser(node: scala.xml.Node, stack: List[scalaxb.ElemName]): Parser[eveapi.xml.map.Sovereignty.Rowset] =
      phrase(safeRep(scalaxb.ElemName(None, "row")) ^^
      { case p1 =>
      eveapi.xml.map.Sovereignty.Rowset(p1.toSeq map { scalaxb.fromXML[eveapi.xml.map.Sovereignty.Row](_, scalaxb.ElemName(node) :: stack) },
        scala.collection.immutable.ListMap(List(
        (node \ "@columns").headOption map { x => scalaxb.DataRecord(x, node, scalaxb.fromXML[String](x, scalaxb.ElemName(node) :: stack)) } map { "@columns" -> _ },
        (node \ "@key").headOption map { x => scalaxb.DataRecord(x, node, scalaxb.fromXML[String](x, scalaxb.ElemName(node) :: stack)) } map { "@key" -> _ },
        (node \ "@name").headOption map { x => scalaxb.DataRecord(x, node, scalaxb.fromXML[String](x, scalaxb.ElemName(node) :: stack)) } map { "@name" -> _ }
        ).flatten[(String, scalaxb.DataRecord[Any])]: _*)) })
    
    override def writesAttribute(__obj: eveapi.xml.map.Sovereignty.Rowset, __scope: scala.xml.NamespaceBinding): scala.xml.MetaData = {
      var attr: scala.xml.MetaData  = scala.xml.Null
      __obj.attributes.toList map {
        case ("@columns", _) => attr = scala.xml.Attribute(null, "columns", __obj.columns.toString, attr)
        case ("@key", _) => attr = scala.xml.Attribute(null, "key", __obj.key.toString, attr)
        case ("@name", _) => attr = scala.xml.Attribute(null, "name", __obj.name.toString, attr)
        case (key, x) => attr = scala.xml.Attribute((x.namespace map { __scope.getPrefix(_) }).orNull, x.key.orNull, x.value.toString, attr)
      }
      attr
    }

    def writesChildNodes(__obj: eveapi.xml.map.Sovereignty.Rowset, __scope: scala.xml.NamespaceBinding): Seq[scala.xml.Node] =
      (__obj.row flatMap { scalaxb.toXML[eveapi.xml.map.Sovereignty.Row](_, None, Some("row"), __scope, false) })

  }

  trait DefaultSovereigntyRowFormat extends scalaxb.XMLFormat[eveapi.xml.map.Sovereignty.Row] with scalaxb.CanWriteChildNodes[eveapi.xml.map.Sovereignty.Row] {
    val targetNamespace: Option[String] = None
    import scalaxb.ElemName._
    
    def reads(seq: scala.xml.NodeSeq, stack: List[scalaxb.ElemName]): Either[String, eveapi.xml.map.Sovereignty.Row] = seq match {
      case node: scala.xml.Node => Right(eveapi.xml.map.Sovereignty.Row(scala.collection.immutable.ListMap(List(
        (node \ "@allianceID").headOption map { x => scalaxb.DataRecord(x, node, scalaxb.fromXML[BigInt](x, scalaxb.ElemName(node) :: stack)) } map { "@allianceID" -> _ },
        (node \ "@corporationID").headOption map { x => scalaxb.DataRecord(x, node, scalaxb.fromXML[BigInt](x, scalaxb.ElemName(node) :: stack)) } map { "@corporationID" -> _ },
        (node \ "@factionID").headOption map { x => scalaxb.DataRecord(x, node, scalaxb.fromXML[BigInt](x, scalaxb.ElemName(node) :: stack)) } map { "@factionID" -> _ },
        (node \ "@solarSystemID").headOption map { x => scalaxb.DataRecord(x, node, scalaxb.fromXML[BigInt](x, scalaxb.ElemName(node) :: stack)) } map { "@solarSystemID" -> _ },
        (node \ "@solarSystemName").headOption map { x => scalaxb.DataRecord(x, node, scalaxb.fromXML[String](x, scalaxb.ElemName(node) :: stack)) } map { "@solarSystemName" -> _ }
        ).flatten[(String, scalaxb.DataRecord[Any])]: _*)))
      case _ => Left("reads failed: seq must be scala.xml.Node")
    }
    
    override def writesAttribute(__obj: eveapi.xml.map.Sovereignty.Row, __scope: scala.xml.NamespaceBinding): scala.xml.MetaData = {
      var attr: scala.xml.MetaData  = scala.xml.Null
      __obj.attributes.toList map {
        case ("@allianceID", _) => attr = scala.xml.Attribute(null, "allianceID", __obj.allianceID.toString, attr)
        case ("@corporationID", _) => attr = scala.xml.Attribute(null, "corporationID", __obj.corporationID.toString, attr)
        case ("@factionID", _) => attr = scala.xml.Attribute(null, "factionID", __obj.factionID.toString, attr)
        case ("@solarSystemID", _) => attr = scala.xml.Attribute(null, "solarSystemID", __obj.solarSystemID.toString, attr)
        case ("@solarSystemName", _) => attr = scala.xml.Attribute(null, "solarSystemName", __obj.solarSystemName.toString, attr)
        case (key, x) => attr = scala.xml.Attribute((x.namespace map { __scope.getPrefix(_) }).orNull, x.key.orNull, x.value.toString, attr)
      }
      attr
    }

    def writesChildNodes(__obj: eveapi.xml.map.Sovereignty.Row, __scope: scala.xml.NamespaceBinding): Seq[scala.xml.Node] =
      Nil


  }


}

