// Generated by <a href="http://scalaxb.org/">scalaxb</a>.
package eveapi.xml.char.ContractItems


case class Eveapi(currentTime: String,
  result: eveapi.xml.char.ContractItems.Result,
  cachedUntil: String,
  attributes: Map[String, scalaxb.DataRecord[Any]] = Map()) {
  lazy val version = attributes("@version").as[BigInt]
}

      


case class Result(rowset: eveapi.xml.char.ContractItems.Rowset)
      


case class Rowset(row: Seq[eveapi.xml.char.ContractItems.Row] = Nil,
  attributes: Map[String, scalaxb.DataRecord[Any]] = Map()) {
  lazy val columns = attributes("@columns").as[String]
  lazy val key = attributes("@key").as[String]
  lazy val name = attributes("@name").as[String]
}

      


case class Row(attributes: Map[String, scalaxb.DataRecord[Any]] = Map()) {
  lazy val included = attributes("@included").as[BigInt]
  lazy val quantity = attributes("@quantity").as[BigInt]
  lazy val recordID = attributes("@recordID").as[BigInt]
  lazy val singleton = attributes("@singleton").as[BigInt]
  lazy val typeID = attributes("@typeID").as[BigInt]
}

      

