// Generated by <a href="http://scalaxb.org/">scalaxb</a>.
package eveapi.xml.account.char.Skills

case class Eveapi(currentTime: String,
                  result: eveapi.xml.account.char.Skills.Result,
                  cachedUntil: String,
                  attributes: Map[String, scalaxb.DataRecord[Any]] = Map()) {
  lazy val version = attributes("@version").as[BigInt]
}

case class Result(freeSkillPoints: BigInt, rowset: eveapi.xml.account.char.Skills.Rowset)

case class Rowset(row: Seq[eveapi.xml.account.char.Skills.Row] = Nil,
                  attributes: Map[String, scalaxb.DataRecord[Any]] = Map()) {
  lazy val columns = attributes("@columns").as[String]
  lazy val key = attributes("@key").as[String]
  lazy val name = attributes("@name").as[String]
}

case class Row(attributes: Map[String, scalaxb.DataRecord[Any]] = Map()) {
  lazy val level = attributes("@level").as[BigInt]
  lazy val published = attributes("@published").as[BigInt]
  lazy val skillpoints = attributes("@skillpoints").as[BigInt]
  lazy val typeID = attributes("@typeID").as[BigInt]
  lazy val typeName = attributes("@typeName").as[String]
}
