// Generated by <a href="http://scalaxb.org/">scalaxb</a>.
package eveapi.xml.corp.ContactList

case class Eveapi(currentTime: String,
                  result: eveapi.xml.corp.ContactList.Result,
                  cachedUntil: String,
                  attributes: Map[String, scalaxb.DataRecord[Any]] = Map()) {
  lazy val version = attributes("@version").as[BigInt]
}

case class Result(rowset: eveapi.xml.corp.ContactList.Rowset*)

case class Rowset(row: Seq[eveapi.xml.corp.ContactList.Row] = Nil,
                  attributes: Map[String, scalaxb.DataRecord[Any]] = Map()) {
  lazy val columns = attributes("@columns").as[String]
  lazy val key = attributes("@key").as[String]
  lazy val name = attributes("@name").as[String]
}

case class Row(attributes: Map[String, scalaxb.DataRecord[Any]] = Map()) {
  lazy val contactID = attributes("@contactID").as[BigInt]
  lazy val contactName = attributes("@contactName").as[String]
  lazy val contactTypeID = attributes("@contactTypeID").as[BigInt]
  lazy val standing = attributes("@standing").as[BigDecimal]
}
