// Generated by <a href="http://scalaxb.org/">scalaxb</a>.
package eveapi.xml.account.char.AssetList

case class Eveapi(currentTime: String,
                  result: eveapi.xml.account.char.AssetList.Result,
                  cachedUntil: String,
                  attributes: Map[String, scalaxb.DataRecord[Any]] = Map()) {
  lazy val version = attributes("@version").as[BigInt]
}

case class Result(rowset: eveapi.xml.account.char.AssetList.Rowset)

case class Rowset(row: Seq[eveapi.xml.account.char.AssetList.Row] = Nil,
                  attributes: Map[String, scalaxb.DataRecord[Any]] = Map()) {
  lazy val columns = attributes("@columns").as[String]
  lazy val key = attributes("@key").as[String]
  lazy val name = attributes("@name").as[String]
}

case class Row(rowset: Option[eveapi.xml.account.char.AssetList.Rowset] = None,
               attributes: Map[String, scalaxb.DataRecord[Any]] = Map()) {
  lazy val flag = attributes("@flag").as[BigInt]
  lazy val itemID = attributes("@itemID").as[BigInt]
  lazy val locationID = attributes.get("@locationID") map { _.as[BigInt] }
  lazy val quantity = attributes("@quantity").as[BigInt]
  lazy val rawQuantity = attributes.get("@rawQuantity") map { _.as[BigInt] }
  lazy val singleton = attributes("@singleton").as[BigInt]
  lazy val typeID = attributes("@typeID").as[BigInt]
}
