// Generated by <a href="http://scalaxb.org/">scalaxb</a>.
package eveapi.xml.char.AssetList

import scala.concurrent.Future


/**
usage:
val obj = scalaxb.fromXML[eveapi.xml.char.AssetList.Foo](node)
val document = scalaxb.toXML[eveapi.xml.char.AssetList.Foo](obj, "foo", eveapi.xml.char.AssetList.defaultScope)
**/
object `package` extends XMLProtocol { }

trait XMLProtocol extends scalaxb.XMLStandardTypes {
  implicit lazy val executionContext = scala.concurrent.ExecutionContext.Implicits.global

  val defaultScope = scalaxb.toScope(Some("xs") -> "http://www.w3.org/2001/XMLSchema",
    Some("xsi") -> "http://www.w3.org/2001/XMLSchema-instance")
  implicit lazy val AssetListEveapiFormat: scalaxb.XMLFormat[eveapi.xml.char.AssetList.Eveapi] = new DefaultAssetListEveapiFormat {}
  implicit lazy val AssetListResultFormat: scalaxb.XMLFormat[eveapi.xml.char.AssetList.Result] = new DefaultAssetListResultFormat {}
  implicit lazy val AssetListRowsetFormat: scalaxb.XMLFormat[eveapi.xml.char.AssetList.Rowset] = new DefaultAssetListRowsetFormat {}
  implicit lazy val AssetListRowFormat: scalaxb.XMLFormat[eveapi.xml.char.AssetList.Row] = new DefaultAssetListRowFormat {}

  trait DefaultAssetListEveapiFormat extends scalaxb.ElemNameParser[eveapi.xml.char.AssetList.Eveapi] {
    val targetNamespace: Option[String] = None
    
    def parser(node: scala.xml.Node, stack: List[scalaxb.ElemName]): Parser[eveapi.xml.char.AssetList.Eveapi] =
      phrase((scalaxb.ElemName(None, "currentTime")) ~ 
      (scalaxb.ElemName(None, "result")) ~ 
      (scalaxb.ElemName(None, "cachedUntil")) ^^
      { case p1 ~ p2 ~ p3 =>
      eveapi.xml.char.AssetList.Eveapi(scalaxb.fromXML[String](p1, scalaxb.ElemName(node) :: stack),
        scalaxb.fromXML[eveapi.xml.char.AssetList.Result](p2, scalaxb.ElemName(node) :: stack),
        scalaxb.fromXML[String](p3, scalaxb.ElemName(node) :: stack),
        scala.collection.immutable.ListMap(List(
        (node \ "@version").headOption map { x => scalaxb.DataRecord(x, node, scalaxb.fromXML[BigInt](x, scalaxb.ElemName(node) :: stack)) } map { "@version" -> _ }
        ).flatten[(String, scalaxb.DataRecord[Any])]: _*)) })
    
    override def writesAttribute(__obj: eveapi.xml.char.AssetList.Eveapi, __scope: scala.xml.NamespaceBinding): scala.xml.MetaData = {
      var attr: scala.xml.MetaData  = scala.xml.Null
      __obj.attributes.toList map {
        case ("@version", _) => attr = scala.xml.Attribute(null, "version", __obj.version.toString, attr)
        case (key, x) => attr = scala.xml.Attribute((x.namespace map { __scope.getPrefix(_) }).orNull, x.key.orNull, x.value.toString, attr)
      }
      attr
    }

    def writesChildNodes(__obj: eveapi.xml.char.AssetList.Eveapi, __scope: scala.xml.NamespaceBinding): Seq[scala.xml.Node] =
      Seq.concat(scalaxb.toXML[String](__obj.currentTime, None, Some("currentTime"), __scope, false),
        scalaxb.toXML[eveapi.xml.char.AssetList.Result](__obj.result, None, Some("result"), __scope, false),
        scalaxb.toXML[String](__obj.cachedUntil, None, Some("cachedUntil"), __scope, false))

  }

  trait DefaultAssetListResultFormat extends scalaxb.ElemNameParser[eveapi.xml.char.AssetList.Result] {
    val targetNamespace: Option[String] = None
    
    def parser(node: scala.xml.Node, stack: List[scalaxb.ElemName]): Parser[eveapi.xml.char.AssetList.Result] =
      phrase((scalaxb.ElemName(None, "rowset")) ^^
      { case p1 =>
      eveapi.xml.char.AssetList.Result(scalaxb.fromXML[eveapi.xml.char.AssetList.Rowset](p1, scalaxb.ElemName(node) :: stack)) })
    
    def writesChildNodes(__obj: eveapi.xml.char.AssetList.Result, __scope: scala.xml.NamespaceBinding): Seq[scala.xml.Node] =
      (scalaxb.toXML[eveapi.xml.char.AssetList.Rowset](__obj.rowset, None, Some("rowset"), __scope, false))

  }

  trait DefaultAssetListRowsetFormat extends scalaxb.ElemNameParser[eveapi.xml.char.AssetList.Rowset] {
    val targetNamespace: Option[String] = None
    
    def parser(node: scala.xml.Node, stack: List[scalaxb.ElemName]): Parser[eveapi.xml.char.AssetList.Rowset] =
      phrase(safeRep(scalaxb.ElemName(None, "row")) ^^
      { case p1 =>
      eveapi.xml.char.AssetList.Rowset(p1.toSeq map { scalaxb.fromXML[eveapi.xml.char.AssetList.Row](_, scalaxb.ElemName(node) :: stack) },
        scala.collection.immutable.ListMap(List(
        (node \ "@columns").headOption map { x => scalaxb.DataRecord(x, node, scalaxb.fromXML[String](x, scalaxb.ElemName(node) :: stack)) } map { "@columns" -> _ },
        (node \ "@key").headOption map { x => scalaxb.DataRecord(x, node, scalaxb.fromXML[String](x, scalaxb.ElemName(node) :: stack)) } map { "@key" -> _ },
        (node \ "@name").headOption map { x => scalaxb.DataRecord(x, node, scalaxb.fromXML[String](x, scalaxb.ElemName(node) :: stack)) } map { "@name" -> _ }
        ).flatten[(String, scalaxb.DataRecord[Any])]: _*)) })
    
    override def writesAttribute(__obj: eveapi.xml.char.AssetList.Rowset, __scope: scala.xml.NamespaceBinding): scala.xml.MetaData = {
      var attr: scala.xml.MetaData  = scala.xml.Null
      __obj.attributes.toList map {
        case ("@columns", _) => attr = scala.xml.Attribute(null, "columns", __obj.columns.toString, attr)
        case ("@key", _) => attr = scala.xml.Attribute(null, "key", __obj.key.toString, attr)
        case ("@name", _) => attr = scala.xml.Attribute(null, "name", __obj.name.toString, attr)
        case (key, x) => attr = scala.xml.Attribute((x.namespace map { __scope.getPrefix(_) }).orNull, x.key.orNull, x.value.toString, attr)
      }
      attr
    }

    def writesChildNodes(__obj: eveapi.xml.char.AssetList.Rowset, __scope: scala.xml.NamespaceBinding): Seq[scala.xml.Node] =
      (__obj.row flatMap { scalaxb.toXML[eveapi.xml.char.AssetList.Row](_, None, Some("row"), __scope, false) })

  }

  trait DefaultAssetListRowFormat extends scalaxb.ElemNameParser[eveapi.xml.char.AssetList.Row] {
    val targetNamespace: Option[String] = None
    
    def parser(node: scala.xml.Node, stack: List[scalaxb.ElemName]): Parser[eveapi.xml.char.AssetList.Row] =
      phrase(opt(scalaxb.ElemName(None, "rowset")) ^^
      { case p1 =>
      eveapi.xml.char.AssetList.Row(p1.headOption map { scalaxb.fromXML[eveapi.xml.char.AssetList.Rowset](_, scalaxb.ElemName(node) :: stack) },
        scala.collection.immutable.ListMap(List(
        (node \ "@flag").headOption map { x => scalaxb.DataRecord(x, node, scalaxb.fromXML[BigInt](x, scalaxb.ElemName(node) :: stack)) } map { "@flag" -> _ },
        (node \ "@itemID").headOption map { x => scalaxb.DataRecord(x, node, scalaxb.fromXML[BigInt](x, scalaxb.ElemName(node) :: stack)) } map { "@itemID" -> _ },
        (node \ "@locationID").headOption map { x => scalaxb.DataRecord(x, node, scalaxb.fromXML[BigInt](x, scalaxb.ElemName(node) :: stack)) } map { "@locationID" -> _ },
        (node \ "@quantity").headOption map { x => scalaxb.DataRecord(x, node, scalaxb.fromXML[BigInt](x, scalaxb.ElemName(node) :: stack)) } map { "@quantity" -> _ },
        (node \ "@rawQuantity").headOption map { x => scalaxb.DataRecord(x, node, scalaxb.fromXML[BigInt](x, scalaxb.ElemName(node) :: stack)) } map { "@rawQuantity" -> _ },
        (node \ "@singleton").headOption map { x => scalaxb.DataRecord(x, node, scalaxb.fromXML[BigInt](x, scalaxb.ElemName(node) :: stack)) } map { "@singleton" -> _ },
        (node \ "@typeID").headOption map { x => scalaxb.DataRecord(x, node, scalaxb.fromXML[BigInt](x, scalaxb.ElemName(node) :: stack)) } map { "@typeID" -> _ }
        ).flatten[(String, scalaxb.DataRecord[Any])]: _*)) })
    
    override def writesAttribute(__obj: eveapi.xml.char.AssetList.Row, __scope: scala.xml.NamespaceBinding): scala.xml.MetaData = {
      var attr: scala.xml.MetaData  = scala.xml.Null
      __obj.attributes.toList map {
        case ("@flag", _) => attr = scala.xml.Attribute(null, "flag", __obj.flag.toString, attr)
        case ("@itemID", _) => attr = scala.xml.Attribute(null, "itemID", __obj.itemID.toString, attr)
        case ("@locationID", _) => __obj.locationID foreach { x => attr = scala.xml.Attribute(null, "locationID", x.toString, attr) }
        case ("@quantity", _) => attr = scala.xml.Attribute(null, "quantity", __obj.quantity.toString, attr)
        case ("@rawQuantity", _) => __obj.rawQuantity foreach { x => attr = scala.xml.Attribute(null, "rawQuantity", x.toString, attr) }
        case ("@singleton", _) => attr = scala.xml.Attribute(null, "singleton", __obj.singleton.toString, attr)
        case ("@typeID", _) => attr = scala.xml.Attribute(null, "typeID", __obj.typeID.toString, attr)
        case (key, x) => attr = scala.xml.Attribute((x.namespace map { __scope.getPrefix(_) }).orNull, x.key.orNull, x.value.toString, attr)
      }
      attr
    }

    def writesChildNodes(__obj: eveapi.xml.char.AssetList.Row, __scope: scala.xml.NamespaceBinding): Seq[scala.xml.Node] =
      (__obj.rowset map { scalaxb.toXML[eveapi.xml.char.AssetList.Rowset](_, None, Some("rowset"), __scope, false) } getOrElse {Nil})

  }


}

