// Generated by <a href="http://scalaxb.org/">scalaxb</a>.
package eveapi.xml.char.Blueprints

case class Eveapi(currentTime: String,
                  result: eveapi.xml.char.Blueprints.Result,
                  cachedUntil: String,
                  attributes: Map[String, scalaxb.DataRecord[Any]] = Map()) {
  lazy val version = attributes("@version").as[BigInt]
}

case class Result(rowset: eveapi.xml.char.Blueprints.Rowset)

case class Rowset(row: Seq[eveapi.xml.char.Blueprints.Row] = Nil,
                  attributes: Map[String, scalaxb.DataRecord[Any]] = Map()) {
  lazy val columns = attributes("@columns").as[String]
  lazy val key = attributes("@key").as[String]
  lazy val name = attributes("@name").as[String]
}

case class Row(attributes: Map[String, scalaxb.DataRecord[Any]] = Map()) {
  lazy val flagID = attributes("@flagID").as[BigInt]
  lazy val itemID = attributes("@itemID").as[BigInt]
  lazy val locationID = attributes("@locationID").as[BigInt]
  lazy val materialEfficiency = attributes("@materialEfficiency").as[BigInt]
  lazy val quantity = attributes("@quantity").as[BigInt]
  lazy val runs = attributes("@runs").as[BigInt]
  lazy val timeEfficiency = attributes("@timeEfficiency").as[BigInt]
  lazy val typeID = attributes("@typeID").as[BigInt]
  lazy val typeName = attributes("@typeName").as[String]
}
