// Generated by <a href="http://scalaxb.org/">scalaxb</a>.
package eveapi.xml.char.UpcomingCalendarEvents

case class Eveapi(currentTime: String,
                  result: eveapi.xml.char.UpcomingCalendarEvents.Result,
                  cachedUntil: String,
                  attributes: Map[String, scalaxb.DataRecord[Any]] = Map()) {
  lazy val version = attributes("@version").as[BigInt]
}

case class Result(rowset: eveapi.xml.char.UpcomingCalendarEvents.Rowset)

case class Rowset(row: Seq[eveapi.xml.char.UpcomingCalendarEvents.Row] = Nil,
                  attributes: Map[String, scalaxb.DataRecord[Any]] = Map()) {
  lazy val columns = attributes("@columns").as[String]
  lazy val key = attributes("@key").as[String]
  lazy val name = attributes("@name").as[String]
}

case class Row(attributes: Map[String, scalaxb.DataRecord[Any]] = Map()) {
  lazy val duration = attributes("@duration").as[BigInt]
  lazy val eventDate = attributes("@eventDate").as[String]
  lazy val eventID = attributes("@eventID").as[BigInt]
  lazy val eventText = attributes("@eventText").as[String]
  lazy val eventTitle = attributes("@eventTitle").as[String]
  lazy val importance = attributes("@importance").as[BigInt]
  lazy val ownerID = attributes("@ownerID").as[BigInt]
  lazy val ownerName = attributes("@ownerName").as[String]
  lazy val ownerTypeID = attributes("@ownerTypeID").as[BigInt]
  lazy val response = attributes("@response").as[String]
}
