// Generated by <a href="http://scalaxb.org/">scalaxb</a>.
package eveapi.xml.account.char.UpcomingCalendarEvents

import scala.concurrent.Future


/**
usage:
val obj = scalaxb.fromXML[eveapi.xml.account.char.UpcomingCalendarEvents.Foo](node)
val document = scalaxb.toXML[eveapi.xml.account.char.UpcomingCalendarEvents.Foo](obj, "foo", eveapi.xml.account.char.UpcomingCalendarEvents.defaultScope)
**/
object `package` extends XMLProtocol { }

trait XMLProtocol extends scalaxb.XMLStandardTypes {
  implicit lazy val executionContext = scala.concurrent.ExecutionContext.Implicits.global

  val defaultScope = scalaxb.toScope(Some("xs") -> "http://www.w3.org/2001/XMLSchema",
    Some("xsi") -> "http://www.w3.org/2001/XMLSchema-instance")
  implicit lazy val UpcomingCalendarEventsEveapiFormat: scalaxb.XMLFormat[eveapi.xml.account.char.UpcomingCalendarEvents.Eveapi] = new DefaultUpcomingCalendarEventsEveapiFormat {}
  implicit lazy val UpcomingCalendarEventsResultFormat: scalaxb.XMLFormat[eveapi.xml.account.char.UpcomingCalendarEvents.Result] = new DefaultUpcomingCalendarEventsResultFormat {}
  implicit lazy val UpcomingCalendarEventsRowsetFormat: scalaxb.XMLFormat[eveapi.xml.account.char.UpcomingCalendarEvents.Rowset] = new DefaultUpcomingCalendarEventsRowsetFormat {}
  implicit lazy val UpcomingCalendarEventsRowFormat: scalaxb.XMLFormat[eveapi.xml.account.char.UpcomingCalendarEvents.Row] = new DefaultUpcomingCalendarEventsRowFormat {}

  trait DefaultUpcomingCalendarEventsEveapiFormat extends scalaxb.ElemNameParser[eveapi.xml.account.char.UpcomingCalendarEvents.Eveapi] {
    val targetNamespace: Option[String] = None
    
    def parser(node: scala.xml.Node, stack: List[scalaxb.ElemName]): Parser[eveapi.xml.account.char.UpcomingCalendarEvents.Eveapi] =
      phrase((scalaxb.ElemName(None, "currentTime")) ~ 
      (scalaxb.ElemName(None, "result")) ~ 
      (scalaxb.ElemName(None, "cachedUntil")) ^^
      { case p1 ~ p2 ~ p3 =>
      eveapi.xml.account.char.UpcomingCalendarEvents.Eveapi(scalaxb.fromXML[String](p1, scalaxb.ElemName(node) :: stack),
        scalaxb.fromXML[eveapi.xml.account.char.UpcomingCalendarEvents.Result](p2, scalaxb.ElemName(node) :: stack),
        scalaxb.fromXML[String](p3, scalaxb.ElemName(node) :: stack),
        scala.collection.immutable.ListMap(List(
        (node \ "@version").headOption map { x => scalaxb.DataRecord(x, node, scalaxb.fromXML[BigInt](x, scalaxb.ElemName(node) :: stack)) } map { "@version" -> _ }
        ).flatten[(String, scalaxb.DataRecord[Any])]: _*)) })
    
    override def writesAttribute(__obj: eveapi.xml.account.char.UpcomingCalendarEvents.Eveapi, __scope: scala.xml.NamespaceBinding): scala.xml.MetaData = {
      var attr: scala.xml.MetaData  = scala.xml.Null
      __obj.attributes.toList map {
        case ("@version", _) => attr = scala.xml.Attribute(null, "version", __obj.version.toString, attr)
        case (key, x) => attr = scala.xml.Attribute((x.namespace map { __scope.getPrefix(_) }).orNull, x.key.orNull, x.value.toString, attr)
      }
      attr
    }

    def writesChildNodes(__obj: eveapi.xml.account.char.UpcomingCalendarEvents.Eveapi, __scope: scala.xml.NamespaceBinding): Seq[scala.xml.Node] =
      Seq.concat(scalaxb.toXML[String](__obj.currentTime, None, Some("currentTime"), __scope, false),
        scalaxb.toXML[eveapi.xml.account.char.UpcomingCalendarEvents.Result](__obj.result, None, Some("result"), __scope, false),
        scalaxb.toXML[String](__obj.cachedUntil, None, Some("cachedUntil"), __scope, false))

  }

  trait DefaultUpcomingCalendarEventsResultFormat extends scalaxb.ElemNameParser[eveapi.xml.account.char.UpcomingCalendarEvents.Result] {
    val targetNamespace: Option[String] = None
    
    def parser(node: scala.xml.Node, stack: List[scalaxb.ElemName]): Parser[eveapi.xml.account.char.UpcomingCalendarEvents.Result] =
      phrase((scalaxb.ElemName(None, "rowset")) ^^
      { case p1 =>
      eveapi.xml.account.char.UpcomingCalendarEvents.Result(scalaxb.fromXML[eveapi.xml.account.char.UpcomingCalendarEvents.Rowset](p1, scalaxb.ElemName(node) :: stack)) })
    
    def writesChildNodes(__obj: eveapi.xml.account.char.UpcomingCalendarEvents.Result, __scope: scala.xml.NamespaceBinding): Seq[scala.xml.Node] =
      (scalaxb.toXML[eveapi.xml.account.char.UpcomingCalendarEvents.Rowset](__obj.rowset, None, Some("rowset"), __scope, false))

  }

  trait DefaultUpcomingCalendarEventsRowsetFormat extends scalaxb.ElemNameParser[eveapi.xml.account.char.UpcomingCalendarEvents.Rowset] {
    val targetNamespace: Option[String] = None
    
    def parser(node: scala.xml.Node, stack: List[scalaxb.ElemName]): Parser[eveapi.xml.account.char.UpcomingCalendarEvents.Rowset] =
      phrase(safeRep(scalaxb.ElemName(None, "row")) ^^
      { case p1 =>
      eveapi.xml.account.char.UpcomingCalendarEvents.Rowset(p1.toSeq map { scalaxb.fromXML[eveapi.xml.account.char.UpcomingCalendarEvents.Row](_, scalaxb.ElemName(node) :: stack) },
        scala.collection.immutable.ListMap(List(
        (node \ "@columns").headOption map { x => scalaxb.DataRecord(x, node, scalaxb.fromXML[String](x, scalaxb.ElemName(node) :: stack)) } map { "@columns" -> _ },
        (node \ "@key").headOption map { x => scalaxb.DataRecord(x, node, scalaxb.fromXML[String](x, scalaxb.ElemName(node) :: stack)) } map { "@key" -> _ },
        (node \ "@name").headOption map { x => scalaxb.DataRecord(x, node, scalaxb.fromXML[String](x, scalaxb.ElemName(node) :: stack)) } map { "@name" -> _ }
        ).flatten[(String, scalaxb.DataRecord[Any])]: _*)) })
    
    override def writesAttribute(__obj: eveapi.xml.account.char.UpcomingCalendarEvents.Rowset, __scope: scala.xml.NamespaceBinding): scala.xml.MetaData = {
      var attr: scala.xml.MetaData  = scala.xml.Null
      __obj.attributes.toList map {
        case ("@columns", _) => attr = scala.xml.Attribute(null, "columns", __obj.columns.toString, attr)
        case ("@key", _) => attr = scala.xml.Attribute(null, "key", __obj.key.toString, attr)
        case ("@name", _) => attr = scala.xml.Attribute(null, "name", __obj.name.toString, attr)
        case (key, x) => attr = scala.xml.Attribute((x.namespace map { __scope.getPrefix(_) }).orNull, x.key.orNull, x.value.toString, attr)
      }
      attr
    }

    def writesChildNodes(__obj: eveapi.xml.account.char.UpcomingCalendarEvents.Rowset, __scope: scala.xml.NamespaceBinding): Seq[scala.xml.Node] =
      (__obj.row flatMap { scalaxb.toXML[eveapi.xml.account.char.UpcomingCalendarEvents.Row](_, None, Some("row"), __scope, false) })

  }

  trait DefaultUpcomingCalendarEventsRowFormat extends scalaxb.XMLFormat[eveapi.xml.account.char.UpcomingCalendarEvents.Row] with scalaxb.CanWriteChildNodes[eveapi.xml.account.char.UpcomingCalendarEvents.Row] {
    val targetNamespace: Option[String] = None
    import scalaxb.ElemName._
    
    def reads(seq: scala.xml.NodeSeq, stack: List[scalaxb.ElemName]): Either[String, eveapi.xml.account.char.UpcomingCalendarEvents.Row] = seq match {
      case node: scala.xml.Node => Right(eveapi.xml.account.char.UpcomingCalendarEvents.Row(scala.collection.immutable.ListMap(List(
        (node \ "@duration").headOption map { x => scalaxb.DataRecord(x, node, scalaxb.fromXML[BigInt](x, scalaxb.ElemName(node) :: stack)) } map { "@duration" -> _ },
        (node \ "@eventDate").headOption map { x => scalaxb.DataRecord(x, node, scalaxb.fromXML[String](x, scalaxb.ElemName(node) :: stack)) } map { "@eventDate" -> _ },
        (node \ "@eventID").headOption map { x => scalaxb.DataRecord(x, node, scalaxb.fromXML[BigInt](x, scalaxb.ElemName(node) :: stack)) } map { "@eventID" -> _ },
        (node \ "@eventText").headOption map { x => scalaxb.DataRecord(x, node, scalaxb.fromXML[String](x, scalaxb.ElemName(node) :: stack)) } map { "@eventText" -> _ },
        (node \ "@eventTitle").headOption map { x => scalaxb.DataRecord(x, node, scalaxb.fromXML[String](x, scalaxb.ElemName(node) :: stack)) } map { "@eventTitle" -> _ },
        (node \ "@importance").headOption map { x => scalaxb.DataRecord(x, node, scalaxb.fromXML[BigInt](x, scalaxb.ElemName(node) :: stack)) } map { "@importance" -> _ },
        (node \ "@ownerID").headOption map { x => scalaxb.DataRecord(x, node, scalaxb.fromXML[BigInt](x, scalaxb.ElemName(node) :: stack)) } map { "@ownerID" -> _ },
        (node \ "@ownerName").headOption map { x => scalaxb.DataRecord(x, node, scalaxb.fromXML[String](x, scalaxb.ElemName(node) :: stack)) } map { "@ownerName" -> _ },
        (node \ "@ownerTypeID").headOption map { x => scalaxb.DataRecord(x, node, scalaxb.fromXML[BigInt](x, scalaxb.ElemName(node) :: stack)) } map { "@ownerTypeID" -> _ },
        (node \ "@response").headOption map { x => scalaxb.DataRecord(x, node, scalaxb.fromXML[String](x, scalaxb.ElemName(node) :: stack)) } map { "@response" -> _ }
        ).flatten[(String, scalaxb.DataRecord[Any])]: _*)))
      case _ => Left("reads failed: seq must be scala.xml.Node")
    }
    
    override def writesAttribute(__obj: eveapi.xml.account.char.UpcomingCalendarEvents.Row, __scope: scala.xml.NamespaceBinding): scala.xml.MetaData = {
      var attr: scala.xml.MetaData  = scala.xml.Null
      __obj.attributes.toList map {
        case ("@duration", _) => attr = scala.xml.Attribute(null, "duration", __obj.duration.toString, attr)
        case ("@eventDate", _) => attr = scala.xml.Attribute(null, "eventDate", __obj.eventDate.toString, attr)
        case ("@eventID", _) => attr = scala.xml.Attribute(null, "eventID", __obj.eventID.toString, attr)
        case ("@eventText", _) => attr = scala.xml.Attribute(null, "eventText", __obj.eventText.toString, attr)
        case ("@eventTitle", _) => attr = scala.xml.Attribute(null, "eventTitle", __obj.eventTitle.toString, attr)
        case ("@importance", _) => attr = scala.xml.Attribute(null, "importance", __obj.importance.toString, attr)
        case ("@ownerID", _) => attr = scala.xml.Attribute(null, "ownerID", __obj.ownerID.toString, attr)
        case ("@ownerName", _) => attr = scala.xml.Attribute(null, "ownerName", __obj.ownerName.toString, attr)
        case ("@ownerTypeID", _) => attr = scala.xml.Attribute(null, "ownerTypeID", __obj.ownerTypeID.toString, attr)
        case ("@response", _) => attr = scala.xml.Attribute(null, "response", __obj.response.toString, attr)
        case (key, x) => attr = scala.xml.Attribute((x.namespace map { __scope.getPrefix(_) }).orNull, x.key.orNull, x.value.toString, attr)
      }
      attr
    }

    def writesChildNodes(__obj: eveapi.xml.account.char.UpcomingCalendarEvents.Row, __scope: scala.xml.NamespaceBinding): Seq[scala.xml.Node] =
      Nil


  }


}

