// Generated by <a href="http://scalaxb.org/">scalaxb</a>.
package eveapi.xml.eve.AllianceList

case class Eveapi(currentTime: String,
                  result: eveapi.xml.eve.AllianceList.Result,
                  cachedUntil: String,
                  attributes: Map[String, scalaxb.DataRecord[Any]] = Map()) {
  lazy val version = attributes("@version").as[BigInt]
}

case class Result(rowset: eveapi.xml.eve.AllianceList.Rowset)

case class Rowset(row: Seq[eveapi.xml.eve.AllianceList.Row] = Nil,
                  attributes: Map[String, scalaxb.DataRecord[Any]] = Map()) {
  lazy val columns = attributes("@columns").as[String]
  lazy val key = attributes("@key").as[String]
  lazy val name = attributes("@name").as[String]
}

case class Row(rowset: Option[eveapi.xml.eve.AllianceList.Rowset] = None,
               attributes: Map[String, scalaxb.DataRecord[Any]] = Map()) {
  lazy val allianceID = attributes.get("@allianceID") map { _.as[BigInt] }
  lazy val corporationID =
    attributes.get("@corporationID") map { _.as[BigInt] }
  lazy val executorCorpID =
    attributes.get("@executorCorpID") map { _.as[BigInt] }
  lazy val memberCount = attributes.get("@memberCount") map { _.as[BigInt] }
  lazy val name = attributes.get("@name") map { _.as[String] }
  lazy val shortName = attributes.get("@shortName") map { _.as[String] }
  lazy val startDate = attributes("@startDate").as[String]
}
