// Generated by <a href="http://scalaxb.org/">scalaxb</a>.
package eveapi.xml.eve.AllianceList

import scala.concurrent.Future


/**
usage:
val obj = scalaxb.fromXML[eveapi.xml.eve.AllianceList.Foo](node)
val document = scalaxb.toXML[eveapi.xml.eve.AllianceList.Foo](obj, "foo", eveapi.xml.eve.AllianceList.defaultScope)
**/
object `package` extends XMLProtocol { }

trait XMLProtocol extends scalaxb.XMLStandardTypes {
  implicit lazy val executionContext = scala.concurrent.ExecutionContext.Implicits.global

  val defaultScope = scalaxb.toScope(Some("xs") -> "http://www.w3.org/2001/XMLSchema",
    Some("xsi") -> "http://www.w3.org/2001/XMLSchema-instance")
  implicit lazy val AllianceListEveapiFormat: scalaxb.XMLFormat[eveapi.xml.eve.AllianceList.Eveapi] = new DefaultAllianceListEveapiFormat {}
  implicit lazy val AllianceListResultFormat: scalaxb.XMLFormat[eveapi.xml.eve.AllianceList.Result] = new DefaultAllianceListResultFormat {}
  implicit lazy val AllianceListRowsetFormat: scalaxb.XMLFormat[eveapi.xml.eve.AllianceList.Rowset] = new DefaultAllianceListRowsetFormat {}
  implicit lazy val AllianceListRowFormat: scalaxb.XMLFormat[eveapi.xml.eve.AllianceList.Row] = new DefaultAllianceListRowFormat {}

  trait DefaultAllianceListEveapiFormat extends scalaxb.ElemNameParser[eveapi.xml.eve.AllianceList.Eveapi] {
    val targetNamespace: Option[String] = None
    
    def parser(node: scala.xml.Node, stack: List[scalaxb.ElemName]): Parser[eveapi.xml.eve.AllianceList.Eveapi] =
      phrase((scalaxb.ElemName(None, "currentTime")) ~ 
      (scalaxb.ElemName(None, "result")) ~ 
      (scalaxb.ElemName(None, "cachedUntil")) ^^
      { case p1 ~ p2 ~ p3 =>
      eveapi.xml.eve.AllianceList.Eveapi(scalaxb.fromXML[String](p1, scalaxb.ElemName(node) :: stack),
        scalaxb.fromXML[eveapi.xml.eve.AllianceList.Result](p2, scalaxb.ElemName(node) :: stack),
        scalaxb.fromXML[String](p3, scalaxb.ElemName(node) :: stack),
        scala.collection.immutable.ListMap(List(
        (node \ "@version").headOption map { x => scalaxb.DataRecord(x, node, scalaxb.fromXML[BigInt](x, scalaxb.ElemName(node) :: stack)) } map { "@version" -> _ }
        ).flatten[(String, scalaxb.DataRecord[Any])]: _*)) })
    
    override def writesAttribute(__obj: eveapi.xml.eve.AllianceList.Eveapi, __scope: scala.xml.NamespaceBinding): scala.xml.MetaData = {
      var attr: scala.xml.MetaData  = scala.xml.Null
      __obj.attributes.toList map {
        case ("@version", _) => attr = scala.xml.Attribute(null, "version", __obj.version.toString, attr)
        case (key, x) => attr = scala.xml.Attribute((x.namespace map { __scope.getPrefix(_) }).orNull, x.key.orNull, x.value.toString, attr)
      }
      attr
    }

    def writesChildNodes(__obj: eveapi.xml.eve.AllianceList.Eveapi, __scope: scala.xml.NamespaceBinding): Seq[scala.xml.Node] =
      Seq.concat(scalaxb.toXML[String](__obj.currentTime, None, Some("currentTime"), __scope, false),
        scalaxb.toXML[eveapi.xml.eve.AllianceList.Result](__obj.result, None, Some("result"), __scope, false),
        scalaxb.toXML[String](__obj.cachedUntil, None, Some("cachedUntil"), __scope, false))

  }

  trait DefaultAllianceListResultFormat extends scalaxb.ElemNameParser[eveapi.xml.eve.AllianceList.Result] {
    val targetNamespace: Option[String] = None
    
    def parser(node: scala.xml.Node, stack: List[scalaxb.ElemName]): Parser[eveapi.xml.eve.AllianceList.Result] =
      phrase((scalaxb.ElemName(None, "rowset")) ^^
      { case p1 =>
      eveapi.xml.eve.AllianceList.Result(scalaxb.fromXML[eveapi.xml.eve.AllianceList.Rowset](p1, scalaxb.ElemName(node) :: stack)) })
    
    def writesChildNodes(__obj: eveapi.xml.eve.AllianceList.Result, __scope: scala.xml.NamespaceBinding): Seq[scala.xml.Node] =
      (scalaxb.toXML[eveapi.xml.eve.AllianceList.Rowset](__obj.rowset, None, Some("rowset"), __scope, false))

  }

  trait DefaultAllianceListRowsetFormat extends scalaxb.ElemNameParser[eveapi.xml.eve.AllianceList.Rowset] {
    val targetNamespace: Option[String] = None
    
    def parser(node: scala.xml.Node, stack: List[scalaxb.ElemName]): Parser[eveapi.xml.eve.AllianceList.Rowset] =
      phrase(safeRep(scalaxb.ElemName(None, "row")) ^^
      { case p1 =>
      eveapi.xml.eve.AllianceList.Rowset(p1.toSeq map { scalaxb.fromXML[eveapi.xml.eve.AllianceList.Row](_, scalaxb.ElemName(node) :: stack) },
        scala.collection.immutable.ListMap(List(
        (node \ "@columns").headOption map { x => scalaxb.DataRecord(x, node, scalaxb.fromXML[String](x, scalaxb.ElemName(node) :: stack)) } map { "@columns" -> _ },
        (node \ "@key").headOption map { x => scalaxb.DataRecord(x, node, scalaxb.fromXML[String](x, scalaxb.ElemName(node) :: stack)) } map { "@key" -> _ },
        (node \ "@name").headOption map { x => scalaxb.DataRecord(x, node, scalaxb.fromXML[String](x, scalaxb.ElemName(node) :: stack)) } map { "@name" -> _ }
        ).flatten[(String, scalaxb.DataRecord[Any])]: _*)) })
    
    override def writesAttribute(__obj: eveapi.xml.eve.AllianceList.Rowset, __scope: scala.xml.NamespaceBinding): scala.xml.MetaData = {
      var attr: scala.xml.MetaData  = scala.xml.Null
      __obj.attributes.toList map {
        case ("@columns", _) => attr = scala.xml.Attribute(null, "columns", __obj.columns.toString, attr)
        case ("@key", _) => attr = scala.xml.Attribute(null, "key", __obj.key.toString, attr)
        case ("@name", _) => attr = scala.xml.Attribute(null, "name", __obj.name.toString, attr)
        case (key, x) => attr = scala.xml.Attribute((x.namespace map { __scope.getPrefix(_) }).orNull, x.key.orNull, x.value.toString, attr)
      }
      attr
    }

    def writesChildNodes(__obj: eveapi.xml.eve.AllianceList.Rowset, __scope: scala.xml.NamespaceBinding): Seq[scala.xml.Node] =
      (__obj.row flatMap { scalaxb.toXML[eveapi.xml.eve.AllianceList.Row](_, None, Some("row"), __scope, false) })

  }

  trait DefaultAllianceListRowFormat extends scalaxb.ElemNameParser[eveapi.xml.eve.AllianceList.Row] {
    val targetNamespace: Option[String] = None
    
    def parser(node: scala.xml.Node, stack: List[scalaxb.ElemName]): Parser[eveapi.xml.eve.AllianceList.Row] =
      phrase(opt(scalaxb.ElemName(None, "rowset")) ^^
      { case p1 =>
      eveapi.xml.eve.AllianceList.Row(p1.headOption map { scalaxb.fromXML[eveapi.xml.eve.AllianceList.Rowset](_, scalaxb.ElemName(node) :: stack) },
        scala.collection.immutable.ListMap(List(
        (node \ "@allianceID").headOption map { x => scalaxb.DataRecord(x, node, scalaxb.fromXML[BigInt](x, scalaxb.ElemName(node) :: stack)) } map { "@allianceID" -> _ },
        (node \ "@corporationID").headOption map { x => scalaxb.DataRecord(x, node, scalaxb.fromXML[BigInt](x, scalaxb.ElemName(node) :: stack)) } map { "@corporationID" -> _ },
        (node \ "@executorCorpID").headOption map { x => scalaxb.DataRecord(x, node, scalaxb.fromXML[BigInt](x, scalaxb.ElemName(node) :: stack)) } map { "@executorCorpID" -> _ },
        (node \ "@memberCount").headOption map { x => scalaxb.DataRecord(x, node, scalaxb.fromXML[BigInt](x, scalaxb.ElemName(node) :: stack)) } map { "@memberCount" -> _ },
        (node \ "@name").headOption map { x => scalaxb.DataRecord(x, node, scalaxb.fromXML[String](x, scalaxb.ElemName(node) :: stack)) } map { "@name" -> _ },
        (node \ "@shortName").headOption map { x => scalaxb.DataRecord(x, node, scalaxb.fromXML[String](x, scalaxb.ElemName(node) :: stack)) } map { "@shortName" -> _ },
        (node \ "@startDate").headOption map { x => scalaxb.DataRecord(x, node, scalaxb.fromXML[String](x, scalaxb.ElemName(node) :: stack)) } map { "@startDate" -> _ }
        ).flatten[(String, scalaxb.DataRecord[Any])]: _*)) })
    
    override def writesAttribute(__obj: eveapi.xml.eve.AllianceList.Row, __scope: scala.xml.NamespaceBinding): scala.xml.MetaData = {
      var attr: scala.xml.MetaData  = scala.xml.Null
      __obj.attributes.toList map {
        case ("@allianceID", _) => __obj.allianceID foreach { x => attr = scala.xml.Attribute(null, "allianceID", x.toString, attr) }
        case ("@corporationID", _) => __obj.corporationID foreach { x => attr = scala.xml.Attribute(null, "corporationID", x.toString, attr) }
        case ("@executorCorpID", _) => __obj.executorCorpID foreach { x => attr = scala.xml.Attribute(null, "executorCorpID", x.toString, attr) }
        case ("@memberCount", _) => __obj.memberCount foreach { x => attr = scala.xml.Attribute(null, "memberCount", x.toString, attr) }
        case ("@name", _) => __obj.name foreach { x => attr = scala.xml.Attribute(null, "name", x.toString, attr) }
        case ("@shortName", _) => __obj.shortName foreach { x => attr = scala.xml.Attribute(null, "shortName", x.toString, attr) }
        case ("@startDate", _) => attr = scala.xml.Attribute(null, "startDate", __obj.startDate.toString, attr)
        case (key, x) => attr = scala.xml.Attribute((x.namespace map { __scope.getPrefix(_) }).orNull, x.key.orNull, x.value.toString, attr)
      }
      attr
    }

    def writesChildNodes(__obj: eveapi.xml.eve.AllianceList.Row, __scope: scala.xml.NamespaceBinding): Seq[scala.xml.Node] =
      (__obj.rowset map { scalaxb.toXML[eveapi.xml.eve.AllianceList.Rowset](_, None, Some("rowset"), __scope, false) } getOrElse {Nil})

  }


}

