// Generated by <a href="http://scalaxb.org/">scalaxb</a>.
package eveapi.xml.account.char.MailBodies

import scala.concurrent.Future

/**
usage:
val obj = scalaxb.fromXML[eveapi.xml.account.char.MailBodies.Foo](node)
val document = scalaxb.toXML[eveapi.xml.account.char.MailBodies.Foo](obj, "foo", eveapi.xml.account.char.MailBodies.defaultScope)
  **/
object `package` extends XMLProtocol {}

trait XMLProtocol extends scalaxb.XMLStandardTypes {
  implicit lazy val executionContext = scala.concurrent.ExecutionContext.Implicits.global

  val defaultScope = scalaxb.toScope(Some("xs") -> "http://www.w3.org/2001/XMLSchema",
                                     Some("xsi") -> "http://www.w3.org/2001/XMLSchema-instance")
  implicit lazy val MailBodiesEveapiFormat: scalaxb.XMLFormat[
      eveapi.xml.account.char.MailBodies.Eveapi] = new DefaultMailBodiesEveapiFormat {}
  implicit lazy val MailBodiesResultFormat: scalaxb.XMLFormat[
      eveapi.xml.account.char.MailBodies.Result] = new DefaultMailBodiesResultFormat {}
  implicit lazy val MailBodiesRowsetFormat: scalaxb.XMLFormat[
      eveapi.xml.account.char.MailBodies.Rowset] = new DefaultMailBodiesRowsetFormat {}
  implicit lazy val MailBodiesRowFormat: scalaxb.XMLFormat[eveapi.xml.account.char.MailBodies.Row] =
    new DefaultMailBodiesRowFormat {}

  trait DefaultMailBodiesEveapiFormat
      extends scalaxb.ElemNameParser[eveapi.xml.account.char.MailBodies.Eveapi] {
    val targetNamespace: Option[String] = None

    def parser(node: scala.xml.Node,
               stack: List[scalaxb.ElemName]): Parser[eveapi.xml.account.char.MailBodies.Eveapi] =
      phrase(
          (scalaxb.ElemName(None, "currentTime")) ~
          (scalaxb.ElemName(None, "result")) ~
          (scalaxb.ElemName(None, "cachedUntil")) ^^ {
        case p1 ~ p2 ~ p3 =>
          eveapi.xml.account.char.MailBodies.Eveapi(
              scalaxb.fromXML[String](p1, scalaxb.ElemName(node) :: stack),
              scalaxb.fromXML[eveapi.xml.account.char.MailBodies.Result](
                  p2, scalaxb.ElemName(node) :: stack),
              scalaxb.fromXML[String](p3, scalaxb.ElemName(node) :: stack),
              scala.collection.immutable.ListMap(List(
                      (node \ "@version").headOption map { x =>
                    scalaxb.DataRecord(
                        x, node, scalaxb.fromXML[BigInt](x, scalaxb.ElemName(node) :: stack))
                  } map { "@version" -> _ }
                  ).flatten[(String, scalaxb.DataRecord[Any])]: _*))
      })

    override def writesAttribute(__obj: eveapi.xml.account.char.MailBodies.Eveapi,
                                 __scope: scala.xml.NamespaceBinding): scala.xml.MetaData = {
      var attr: scala.xml.MetaData = scala.xml.Null
      __obj.attributes.toList map {
        case ("@version", _) =>
          attr = scala.xml.Attribute(null, "version", __obj.version.toString, attr)
        case (key, x) =>
          attr = scala.xml.Attribute((x.namespace map { __scope.getPrefix(_) }).orNull,
                                     x.key.orNull,
                                     x.value.toString,
                                     attr)
      }
      attr
    }

    def writesChildNodes(__obj: eveapi.xml.account.char.MailBodies.Eveapi,
                         __scope: scala.xml.NamespaceBinding): Seq[scala.xml.Node] =
      Seq.concat(
          scalaxb.toXML[String](__obj.currentTime, None, Some("currentTime"), __scope, false),
          scalaxb.toXML[eveapi.xml.account.char.MailBodies.Result](
              __obj.result, None, Some("result"), __scope, false),
          scalaxb.toXML[String](__obj.cachedUntil, None, Some("cachedUntil"), __scope, false))
  }

  trait DefaultMailBodiesResultFormat
      extends scalaxb.ElemNameParser[eveapi.xml.account.char.MailBodies.Result] {
    val targetNamespace: Option[String] = None

    def parser(node: scala.xml.Node,
               stack: List[scalaxb.ElemName]): Parser[eveapi.xml.account.char.MailBodies.Result] =
      phrase(
          (scalaxb.ElemName(None, "rowset")) ^^ {
        case p1 =>
          eveapi.xml.account.char.MailBodies
            .Result(scalaxb.fromXML[eveapi.xml.account.char.MailBodies.Rowset](
                  p1, scalaxb.ElemName(node) :: stack))
      })

    def writesChildNodes(__obj: eveapi.xml.account.char.MailBodies.Result,
                         __scope: scala.xml.NamespaceBinding): Seq[scala.xml.Node] =
      (scalaxb.toXML[eveapi.xml.account.char.MailBodies.Rowset](
          __obj.rowset, None, Some("rowset"), __scope, false))
  }

  trait DefaultMailBodiesRowsetFormat
      extends scalaxb.ElemNameParser[eveapi.xml.account.char.MailBodies.Rowset] {
    val targetNamespace: Option[String] = None

    def parser(node: scala.xml.Node,
               stack: List[scalaxb.ElemName]): Parser[eveapi.xml.account.char.MailBodies.Rowset] =
      phrase(
          (scalaxb.ElemName(None, "row")) ^^ {
        case p1 =>
          eveapi.xml.account.char.MailBodies.Rowset(
              scalaxb.fromXML[eveapi.xml.account.char.MailBodies.Row](
                  p1, scalaxb.ElemName(node) :: stack),
              scala.collection.immutable.ListMap(List(
                      (node \ "@columns").headOption map { x =>
                    scalaxb.DataRecord(
                        x, node, scalaxb.fromXML[String](x, scalaxb.ElemName(node) :: stack))
                  } map { "@columns" -> _ },
                      (node \ "@key").headOption map { x =>
                    scalaxb.DataRecord(
                        x, node, scalaxb.fromXML[String](x, scalaxb.ElemName(node) :: stack))
                  } map { "@key" -> _ },
                      (node \ "@name").headOption map { x =>
                    scalaxb.DataRecord(
                        x, node, scalaxb.fromXML[String](x, scalaxb.ElemName(node) :: stack))
                  } map { "@name" -> _ }
                  ).flatten[(String, scalaxb.DataRecord[Any])]: _*))
      })

    override def writesAttribute(__obj: eveapi.xml.account.char.MailBodies.Rowset,
                                 __scope: scala.xml.NamespaceBinding): scala.xml.MetaData = {
      var attr: scala.xml.MetaData = scala.xml.Null
      __obj.attributes.toList map {
        case ("@columns", _) =>
          attr = scala.xml.Attribute(null, "columns", __obj.columns.toString, attr)
        case ("@key", _) => attr = scala.xml.Attribute(null, "key", __obj.key.toString, attr)
        case ("@name", _) => attr = scala.xml.Attribute(null, "name", __obj.name.toString, attr)
        case (key, x) =>
          attr = scala.xml.Attribute((x.namespace map { __scope.getPrefix(_) }).orNull,
                                     x.key.orNull,
                                     x.value.toString,
                                     attr)
      }
      attr
    }

    def writesChildNodes(__obj: eveapi.xml.account.char.MailBodies.Rowset,
                         __scope: scala.xml.NamespaceBinding): Seq[scala.xml.Node] =
      (scalaxb.toXML[eveapi.xml.account.char.MailBodies.Row](
          __obj.row, None, Some("row"), __scope, false))
  }

  trait DefaultMailBodiesRowFormat
      extends scalaxb.ElemNameParser[eveapi.xml.account.char.MailBodies.Row] {
    val targetNamespace: Option[String] = None

    override def isMixed: Boolean = true

    def parser(node: scala.xml.Node,
               stack: List[scalaxb.ElemName]): Parser[eveapi.xml.account.char.MailBodies.Row] =
      phrase(
          optTextRecord ^^ {
        case p1 =>
          eveapi.xml.account.char.MailBodies.Row(
              Seq.concat(p1.toList),
              scala.collection.immutable.ListMap(List(
                      (node \ "@messageID").headOption map { x =>
                    scalaxb.DataRecord(
                        x, node, scalaxb.fromXML[BigInt](x, scalaxb.ElemName(node) :: stack))
                  } map { "@messageID" -> _ }
                  ).flatten[(String, scalaxb.DataRecord[Any])]: _*))
      })

    override def writesAttribute(__obj: eveapi.xml.account.char.MailBodies.Row,
                                 __scope: scala.xml.NamespaceBinding): scala.xml.MetaData = {
      var attr: scala.xml.MetaData = scala.xml.Null
      __obj.attributes.toList map {
        case ("@messageID", _) =>
          attr = scala.xml.Attribute(null, "messageID", __obj.messageID.toString, attr)
        case (key, x) =>
          attr = scala.xml.Attribute((x.namespace map { __scope.getPrefix(_) }).orNull,
                                     x.key.orNull,
                                     x.value.toString,
                                     attr)
      }
      attr
    }

    def writesChildNodes(__obj: eveapi.xml.account.char.MailBodies.Row,
                         __scope: scala.xml.NamespaceBinding): Seq[scala.xml.Node] =
      __obj.mixed.toSeq flatMap { x =>
        scalaxb.toXML[scalaxb.DataRecord[Any]](x, x.namespace, x.key, __scope, false)
      }
  }
}
