// Generated by <a href="http://scalaxb.org/">scalaxb</a>.
package eveapi.xml.account.char.Standings

case class Eveapi(currentTime: String,
                  result: eveapi.xml.account.char.Standings.Result,
                  cachedUntil: String,
                  attributes: Map[String, scalaxb.DataRecord[Any]] = Map()) {
  lazy val version = attributes("@version").as[BigInt]
}

case class Result(characterNPCStandings: eveapi.xml.account.char.Standings.CharacterNPCStandings)

case class CharacterNPCStandings(rowset: eveapi.xml.account.char.Standings.Rowset*)

case class Rowset(row: Seq[eveapi.xml.account.char.Standings.Row] = Nil,
                  attributes: Map[String, scalaxb.DataRecord[Any]] = Map()) {
  lazy val columns = attributes("@columns").as[String]
  lazy val key = attributes("@key").as[String]
  lazy val name = attributes("@name").as[String]
}

case class Row(attributes: Map[String, scalaxb.DataRecord[Any]] = Map()) {
  lazy val fromID = attributes("@fromID").as[BigInt]
  lazy val fromName = attributes("@fromName").as[String]
  lazy val standing = attributes("@standing").as[BigDecimal]
}
