// Generated by <a href="http://scalaxb.org/">scalaxb</a>.
package eveapi.xml.account.char.SkillQueue

case class Eveapi(currentTime: String,
                  result: eveapi.xml.account.char.SkillQueue.Result,
                  cachedUntil: String,
                  attributes: Map[String, scalaxb.DataRecord[Any]] = Map()) {
  lazy val version = attributes("@version").as[BigInt]
}

case class Result(rowset: eveapi.xml.account.char.SkillQueue.Rowset)

case class Rowset(row: Seq[eveapi.xml.account.char.SkillQueue.Row] = Nil,
                  attributes: Map[String, scalaxb.DataRecord[Any]] = Map()) {
  lazy val columns = attributes("@columns").as[String]
  lazy val key = attributes("@key").as[String]
  lazy val name = attributes("@name").as[String]
}

case class Row(attributes: Map[String, scalaxb.DataRecord[Any]] = Map()) {
  lazy val endSP = attributes("@endSP").as[BigInt]
  lazy val endTime = attributes("@endTime").as[String]
  lazy val level = attributes("@level").as[BigInt]
  lazy val queuePosition = attributes("@queuePosition").as[BigInt]
  lazy val startSP = attributes("@startSP").as[BigInt]
  lazy val startTime = attributes("@startTime").as[String]
  lazy val typeID = attributes("@typeID").as[BigInt]
}
