// Generated by <a href="http://scalaxb.org/">scalaxb</a>.
package eveapi.xml.eve.ConquerableStationList

case class Eveapi(currentTime: String,
                  result: eveapi.xml.eve.ConquerableStationList.Result,
                  cachedUntil: String,
                  attributes: Map[String, scalaxb.DataRecord[Any]] = Map()) {
  lazy val version = attributes("@version").as[BigInt]
}

case class Result(rowset: eveapi.xml.eve.ConquerableStationList.Rowset)

case class Rowset(row: Seq[eveapi.xml.eve.ConquerableStationList.Row] = Nil,
                  attributes: Map[String, scalaxb.DataRecord[Any]] = Map()) {
  lazy val columns = attributes("@columns").as[String]
  lazy val key = attributes("@key").as[String]
  lazy val name = attributes("@name").as[String]
}

case class Row(attributes: Map[String, scalaxb.DataRecord[Any]] = Map()) {
  lazy val corporationID = attributes("@corporationID").as[BigInt]
  lazy val corporationName = attributes("@corporationName").as[String]
  lazy val solarSystemID = attributes("@solarSystemID").as[BigInt]
  lazy val stationID = attributes("@stationID").as[BigInt]
  lazy val stationName = attributes("@stationName").as[String]
  lazy val stationTypeID = attributes("@stationTypeID").as[BigInt]
}
