// Generated by <a href="http://scalaxb.org/">scalaxb</a>.
package eveapi.xml.account.char.Notifications

case class Eveapi(currentTime: String,
                  result: eveapi.xml.account.char.Notifications.Result,
                  cachedUntil: String,
                  attributes: Map[String, scalaxb.DataRecord[Any]] = Map()) {
  lazy val version = attributes("@version").as[BigInt]
}

case class Result(rowset: eveapi.xml.account.char.Notifications.Rowset)

case class Rowset(row: Seq[eveapi.xml.account.char.Notifications.Row] = Nil,
                  attributes: Map[String, scalaxb.DataRecord[Any]] = Map()) {
  lazy val columns = attributes("@columns").as[String]
  lazy val key = attributes("@key").as[String]
  lazy val name = attributes("@name").as[String]
}

case class Row(attributes: Map[String, scalaxb.DataRecord[Any]] = Map()) {
  lazy val notificationID = attributes("@notificationID").as[BigInt]
  lazy val read = attributes("@read").as[BigInt]
  lazy val senderID = attributes("@senderID").as[BigInt]
  lazy val senderName = attributes("@senderName").as[String]
  lazy val sentDate = attributes("@sentDate").as[String]
  lazy val typeID = attributes("@typeID").as[BigInt]
}
