// Generated by <a href="http://scalaxb.org/">scalaxb</a>.
package eveapi.xml.char.KillMails


case class Eveapi(currentTime: String,
  result: eveapi.xml.char.KillMails.Result,
  cachedUntil: String,
  attributes: Map[String, scalaxb.DataRecord[Any]] = Map()) {
  lazy val version = attributes("@version").as[BigInt]
}

      


case class Result(rowset: eveapi.xml.char.KillMails.Rowset)
      


case class Rowset(row: Seq[eveapi.xml.char.KillMails.Row] = Nil,
  attributes: Map[String, scalaxb.DataRecord[Any]] = Map()) {
  lazy val columns = attributes("@columns").as[String]
  lazy val key = attributes.get("@key") map { _.as[String] }
  lazy val name = attributes("@name").as[String]
}

      


case class Row(victim: Option[eveapi.xml.char.KillMails.Victim] = None,
  rowset: Option[eveapi.xml.char.KillMails.Rowset] = None,
  attributes: Map[String, scalaxb.DataRecord[Any]] = Map()) {
  lazy val allianceID = attributes.get("@allianceID") map { _.as[BigInt] }
  lazy val allianceName = attributes.get("@allianceName") map { _.as[String] }
  lazy val characterID = attributes.get("@characterID") map { _.as[BigInt] }
  lazy val characterName = attributes.get("@characterName") map { _.as[String] }
  lazy val corporationID = attributes.get("@corporationID") map { _.as[BigInt] }
  lazy val corporationName = attributes.get("@corporationName") map { _.as[String] }
  lazy val damageDone = attributes.get("@damageDone") map { _.as[BigInt] }
  lazy val factionID = attributes.get("@factionID") map { _.as[BigInt] }
  lazy val factionName = attributes.get("@factionName") map { _.as[String] }
  lazy val finalBlow = attributes.get("@finalBlow") map { _.as[BigInt] }
  lazy val flag = attributes.get("@flag") map { _.as[BigInt] }
  lazy val killID = attributes.get("@killID") map { _.as[BigInt] }
  lazy val killTime = attributes.get("@killTime") map { _.as[String] }
  lazy val moonID = attributes.get("@moonID") map { _.as[BigInt] }
  lazy val qtyDestroyed = attributes.get("@qtyDestroyed") map { _.as[BigInt] }
  lazy val qtyDropped = attributes.get("@qtyDropped") map { _.as[BigInt] }
  lazy val securityStatus = attributes.get("@securityStatus") map { _.as[BigDecimal] }
  lazy val shipTypeID = attributes.get("@shipTypeID") map { _.as[BigInt] }
  lazy val singleton = attributes.get("@singleton") map { _.as[BigInt] }
  lazy val solarSystemID = attributes.get("@solarSystemID") map { _.as[BigInt] }
  lazy val typeID = attributes.get("@typeID") map { _.as[BigInt] }
  lazy val weaponTypeID = attributes.get("@weaponTypeID") map { _.as[BigInt] }
}

      


case class Victim(attributes: Map[String, scalaxb.DataRecord[Any]] = Map()) {
  lazy val allianceID = attributes("@allianceID").as[BigInt]
  lazy val allianceName = attributes("@allianceName").as[String]
  lazy val characterID = attributes("@characterID").as[BigInt]
  lazy val characterName = attributes("@characterName").as[String]
  lazy val corporationID = attributes("@corporationID").as[BigInt]
  lazy val corporationName = attributes("@corporationName").as[String]
  lazy val damageTaken = attributes("@damageTaken").as[BigInt]
  lazy val factionID = attributes("@factionID").as[BigInt]
  lazy val factionName = attributes("@factionName").as[String]
  lazy val shipTypeID = attributes("@shipTypeID").as[BigInt]
}

      

