// Generated by <a href="http://scalaxb.org/">scalaxb</a>.
package eveapi.xml.account.eve.FacWarStats


case class Eveapi(currentTime: String,
  result: eveapi.xml.account.eve.FacWarStats.Result,
  cachedUntil: String,
  attributes: Map[String, scalaxb.DataRecord[Any]] = Map()) {
  lazy val version = attributes("@version").as[BigInt]
}

      


case class Result(totals: eveapi.xml.account.eve.FacWarStats.Totals,
  rowset: Seq[eveapi.xml.account.eve.FacWarStats.Rowset] = Nil)
      


case class Totals(killsYesterday: BigInt,
  killsLastWeek: BigInt,
  killsTotal: BigInt,
  victoryPointsYesterday: BigInt,
  victoryPointsLastWeek: BigInt,
  victoryPointsTotal: BigInt)
      


case class Rowset(row: Seq[eveapi.xml.account.eve.FacWarStats.Row] = Nil,
  attributes: Map[String, scalaxb.DataRecord[Any]] = Map()) {
  lazy val columns = attributes("@columns").as[String]
  lazy val key = attributes.get("@key") map { _.as[String] }
  lazy val name = attributes("@name").as[String]
}

      


case class Row(attributes: Map[String, scalaxb.DataRecord[Any]] = Map()) {
  lazy val againstID = attributes.get("@againstID") map { _.as[BigInt] }
  lazy val againstName = attributes.get("@againstName") map { _.as[String] }
  lazy val factionID = attributes("@factionID").as[BigInt]
  lazy val factionName = attributes("@factionName").as[String]
  lazy val killsLastWeek = attributes.get("@killsLastWeek") map { _.as[BigInt] }
  lazy val killsTotal = attributes.get("@killsTotal") map { _.as[BigInt] }
  lazy val killsYesterday = attributes.get("@killsYesterday") map { _.as[BigInt] }
  lazy val pilots = attributes.get("@pilots") map { _.as[BigInt] }
  lazy val systemsControlled = attributes.get("@systemsControlled") map { _.as[BigInt] }
  lazy val victoryPointsLastWeek = attributes.get("@victoryPointsLastWeek") map { _.as[BigInt] }
  lazy val victoryPointsTotal = attributes.get("@victoryPointsTotal") map { _.as[BigInt] }
  lazy val victoryPointsYesterday = attributes.get("@victoryPointsYesterday") map { _.as[BigInt] }
}

      

