// Generated by <a href="http://scalaxb.org/">scalaxb</a>.
package eveapi.xml.account.char.MailMessages


case class Eveapi(currentTime: String,
  result: eveapi.xml.account.char.MailMessages.Result,
  cachedUntil: String,
  attributes: Map[String, scalaxb.DataRecord[Any]] = Map()) {
  lazy val version = attributes("@version").as[BigInt]
}

      


case class Result(rowset: eveapi.xml.account.char.MailMessages.Rowset)
      


case class Rowset(row: Seq[eveapi.xml.account.char.MailMessages.Row] = Nil,
  attributes: Map[String, scalaxb.DataRecord[Any]] = Map()) {
  lazy val columns = attributes("@columns").as[String]
  lazy val key = attributes("@key").as[String]
  lazy val name = attributes("@name").as[String]
}

      


case class Row(attributes: Map[String, scalaxb.DataRecord[Any]] = Map()) {
  lazy val messageID = attributes("@messageID").as[BigInt]
  lazy val senderID = attributes("@senderID").as[BigInt]
  lazy val senderName = attributes("@senderName").as[String]
  lazy val senderTypeID = attributes("@senderTypeID").as[BigInt]
  lazy val sentDate = attributes("@sentDate").as[String]
  lazy val title = attributes("@title").as[String]
  lazy val toCharacterIDs = attributes("@toCharacterIDs").as[String]
  lazy val toCorpOrAllianceID = attributes("@toCorpOrAllianceID").as[String]
  lazy val toListID = attributes("@toListID").as[String]
}

      

