// Generated by <a href="http://scalaxb.org/">scalaxb</a>.
package eveapi.xml.char.MailMessages

import scala.concurrent.Future


/**
usage:
val obj = scalaxb.fromXML[eveapi.xml.char.MailMessages.Foo](node)
val document = scalaxb.toXML[eveapi.xml.char.MailMessages.Foo](obj, "foo", eveapi.xml.char.MailMessages.defaultScope)
**/
object `package` extends XMLProtocol { }

trait XMLProtocol extends scalaxb.XMLStandardTypes {
  implicit lazy val executionContext = scala.concurrent.ExecutionContext.Implicits.global

  val defaultScope = scalaxb.toScope(Some("xs") -> "http://www.w3.org/2001/XMLSchema",
    Some("xsi") -> "http://www.w3.org/2001/XMLSchema-instance")
  implicit lazy val MailMessagesEveapiFormat: scalaxb.XMLFormat[eveapi.xml.char.MailMessages.Eveapi] = new DefaultMailMessagesEveapiFormat {}
  implicit lazy val MailMessagesResultFormat: scalaxb.XMLFormat[eveapi.xml.char.MailMessages.Result] = new DefaultMailMessagesResultFormat {}
  implicit lazy val MailMessagesRowsetFormat: scalaxb.XMLFormat[eveapi.xml.char.MailMessages.Rowset] = new DefaultMailMessagesRowsetFormat {}
  implicit lazy val MailMessagesRowFormat: scalaxb.XMLFormat[eveapi.xml.char.MailMessages.Row] = new DefaultMailMessagesRowFormat {}

  trait DefaultMailMessagesEveapiFormat extends scalaxb.ElemNameParser[eveapi.xml.char.MailMessages.Eveapi] {
    val targetNamespace: Option[String] = None
    
    def parser(node: scala.xml.Node, stack: List[scalaxb.ElemName]): Parser[eveapi.xml.char.MailMessages.Eveapi] =
      phrase((scalaxb.ElemName(None, "currentTime")) ~ 
      (scalaxb.ElemName(None, "result")) ~ 
      (scalaxb.ElemName(None, "cachedUntil")) ^^
      { case p1 ~ p2 ~ p3 =>
      eveapi.xml.char.MailMessages.Eveapi(scalaxb.fromXML[String](p1, scalaxb.ElemName(node) :: stack),
        scalaxb.fromXML[eveapi.xml.char.MailMessages.Result](p2, scalaxb.ElemName(node) :: stack),
        scalaxb.fromXML[String](p3, scalaxb.ElemName(node) :: stack),
        scala.collection.immutable.ListMap(List(
        (node \ "@version").headOption map { x => scalaxb.DataRecord(x, node, scalaxb.fromXML[BigInt](x, scalaxb.ElemName(node) :: stack)) } map { "@version" -> _ }
        ).flatten[(String, scalaxb.DataRecord[Any])]: _*)) })
    
    override def writesAttribute(__obj: eveapi.xml.char.MailMessages.Eveapi, __scope: scala.xml.NamespaceBinding): scala.xml.MetaData = {
      var attr: scala.xml.MetaData  = scala.xml.Null
      __obj.attributes.toList map {
        case ("@version", _) => attr = scala.xml.Attribute(null, "version", __obj.version.toString, attr)
        case (key, x) => attr = scala.xml.Attribute((x.namespace map { __scope.getPrefix(_) }).orNull, x.key.orNull, x.value.toString, attr)
      }
      attr
    }

    def writesChildNodes(__obj: eveapi.xml.char.MailMessages.Eveapi, __scope: scala.xml.NamespaceBinding): Seq[scala.xml.Node] =
      Seq.concat(scalaxb.toXML[String](__obj.currentTime, None, Some("currentTime"), __scope, false),
        scalaxb.toXML[eveapi.xml.char.MailMessages.Result](__obj.result, None, Some("result"), __scope, false),
        scalaxb.toXML[String](__obj.cachedUntil, None, Some("cachedUntil"), __scope, false))

  }

  trait DefaultMailMessagesResultFormat extends scalaxb.ElemNameParser[eveapi.xml.char.MailMessages.Result] {
    val targetNamespace: Option[String] = None
    
    def parser(node: scala.xml.Node, stack: List[scalaxb.ElemName]): Parser[eveapi.xml.char.MailMessages.Result] =
      phrase((scalaxb.ElemName(None, "rowset")) ^^
      { case p1 =>
      eveapi.xml.char.MailMessages.Result(scalaxb.fromXML[eveapi.xml.char.MailMessages.Rowset](p1, scalaxb.ElemName(node) :: stack)) })
    
    def writesChildNodes(__obj: eveapi.xml.char.MailMessages.Result, __scope: scala.xml.NamespaceBinding): Seq[scala.xml.Node] =
      (scalaxb.toXML[eveapi.xml.char.MailMessages.Rowset](__obj.rowset, None, Some("rowset"), __scope, false))

  }

  trait DefaultMailMessagesRowsetFormat extends scalaxb.ElemNameParser[eveapi.xml.char.MailMessages.Rowset] {
    val targetNamespace: Option[String] = None
    
    def parser(node: scala.xml.Node, stack: List[scalaxb.ElemName]): Parser[eveapi.xml.char.MailMessages.Rowset] =
      phrase(safeRep(scalaxb.ElemName(None, "row")) ^^
      { case p1 =>
      eveapi.xml.char.MailMessages.Rowset(p1.toSeq map { scalaxb.fromXML[eveapi.xml.char.MailMessages.Row](_, scalaxb.ElemName(node) :: stack) },
        scala.collection.immutable.ListMap(List(
        (node \ "@columns").headOption map { x => scalaxb.DataRecord(x, node, scalaxb.fromXML[String](x, scalaxb.ElemName(node) :: stack)) } map { "@columns" -> _ },
        (node \ "@key").headOption map { x => scalaxb.DataRecord(x, node, scalaxb.fromXML[String](x, scalaxb.ElemName(node) :: stack)) } map { "@key" -> _ },
        (node \ "@name").headOption map { x => scalaxb.DataRecord(x, node, scalaxb.fromXML[String](x, scalaxb.ElemName(node) :: stack)) } map { "@name" -> _ }
        ).flatten[(String, scalaxb.DataRecord[Any])]: _*)) })
    
    override def writesAttribute(__obj: eveapi.xml.char.MailMessages.Rowset, __scope: scala.xml.NamespaceBinding): scala.xml.MetaData = {
      var attr: scala.xml.MetaData  = scala.xml.Null
      __obj.attributes.toList map {
        case ("@columns", _) => attr = scala.xml.Attribute(null, "columns", __obj.columns.toString, attr)
        case ("@key", _) => attr = scala.xml.Attribute(null, "key", __obj.key.toString, attr)
        case ("@name", _) => attr = scala.xml.Attribute(null, "name", __obj.name.toString, attr)
        case (key, x) => attr = scala.xml.Attribute((x.namespace map { __scope.getPrefix(_) }).orNull, x.key.orNull, x.value.toString, attr)
      }
      attr
    }

    def writesChildNodes(__obj: eveapi.xml.char.MailMessages.Rowset, __scope: scala.xml.NamespaceBinding): Seq[scala.xml.Node] =
      (__obj.row flatMap { scalaxb.toXML[eveapi.xml.char.MailMessages.Row](_, None, Some("row"), __scope, false) })

  }

  trait DefaultMailMessagesRowFormat extends scalaxb.XMLFormat[eveapi.xml.char.MailMessages.Row] with scalaxb.CanWriteChildNodes[eveapi.xml.char.MailMessages.Row] {
    val targetNamespace: Option[String] = None
    import scalaxb.ElemName._
    
    def reads(seq: scala.xml.NodeSeq, stack: List[scalaxb.ElemName]): Either[String, eveapi.xml.char.MailMessages.Row] = seq match {
      case node: scala.xml.Node => Right(eveapi.xml.char.MailMessages.Row(scala.collection.immutable.ListMap(List(
        (node \ "@messageID").headOption map { x => scalaxb.DataRecord(x, node, scalaxb.fromXML[BigInt](x, scalaxb.ElemName(node) :: stack)) } map { "@messageID" -> _ },
        (node \ "@senderID").headOption map { x => scalaxb.DataRecord(x, node, scalaxb.fromXML[BigInt](x, scalaxb.ElemName(node) :: stack)) } map { "@senderID" -> _ },
        (node \ "@senderName").headOption map { x => scalaxb.DataRecord(x, node, scalaxb.fromXML[String](x, scalaxb.ElemName(node) :: stack)) } map { "@senderName" -> _ },
        (node \ "@senderTypeID").headOption map { x => scalaxb.DataRecord(x, node, scalaxb.fromXML[BigInt](x, scalaxb.ElemName(node) :: stack)) } map { "@senderTypeID" -> _ },
        (node \ "@sentDate").headOption map { x => scalaxb.DataRecord(x, node, scalaxb.fromXML[String](x, scalaxb.ElemName(node) :: stack)) } map { "@sentDate" -> _ },
        (node \ "@title").headOption map { x => scalaxb.DataRecord(x, node, scalaxb.fromXML[String](x, scalaxb.ElemName(node) :: stack)) } map { "@title" -> _ },
        (node \ "@toCharacterIDs").headOption map { x => scalaxb.DataRecord(x, node, scalaxb.fromXML[String](x, scalaxb.ElemName(node) :: stack)) } map { "@toCharacterIDs" -> _ },
        (node \ "@toCorpOrAllianceID").headOption map { x => scalaxb.DataRecord(x, node, scalaxb.fromXML[String](x, scalaxb.ElemName(node) :: stack)) } map { "@toCorpOrAllianceID" -> _ },
        (node \ "@toListID").headOption map { x => scalaxb.DataRecord(x, node, scalaxb.fromXML[String](x, scalaxb.ElemName(node) :: stack)) } map { "@toListID" -> _ }
        ).flatten[(String, scalaxb.DataRecord[Any])]: _*)))
      case _ => Left("reads failed: seq must be scala.xml.Node")
    }
    
    override def writesAttribute(__obj: eveapi.xml.char.MailMessages.Row, __scope: scala.xml.NamespaceBinding): scala.xml.MetaData = {
      var attr: scala.xml.MetaData  = scala.xml.Null
      __obj.attributes.toList map {
        case ("@messageID", _) => attr = scala.xml.Attribute(null, "messageID", __obj.messageID.toString, attr)
        case ("@senderID", _) => attr = scala.xml.Attribute(null, "senderID", __obj.senderID.toString, attr)
        case ("@senderName", _) => attr = scala.xml.Attribute(null, "senderName", __obj.senderName.toString, attr)
        case ("@senderTypeID", _) => attr = scala.xml.Attribute(null, "senderTypeID", __obj.senderTypeID.toString, attr)
        case ("@sentDate", _) => attr = scala.xml.Attribute(null, "sentDate", __obj.sentDate.toString, attr)
        case ("@title", _) => attr = scala.xml.Attribute(null, "title", __obj.title.toString, attr)
        case ("@toCharacterIDs", _) => attr = scala.xml.Attribute(null, "toCharacterIDs", __obj.toCharacterIDs.toString, attr)
        case ("@toCorpOrAllianceID", _) => attr = scala.xml.Attribute(null, "toCorpOrAllianceID", __obj.toCorpOrAllianceID.toString, attr)
        case ("@toListID", _) => attr = scala.xml.Attribute(null, "toListID", __obj.toListID.toString, attr)
        case (key, x) => attr = scala.xml.Attribute((x.namespace map { __scope.getPrefix(_) }).orNull, x.key.orNull, x.value.toString, attr)
      }
      attr
    }

    def writesChildNodes(__obj: eveapi.xml.char.MailMessages.Row, __scope: scala.xml.NamespaceBinding): Seq[scala.xml.Node] =
      Nil


  }


}

