// Generated by <a href="http://scalaxb.org/">scalaxb</a>.
package eveapi.xml.account.map.Jumps

case class Eveapi(currentTime: String,
                  result: eveapi.xml.account.map.Jumps.Result,
                  cachedUntil: String,
                  attributes: Map[String, scalaxb.DataRecord[Any]] = Map()) {
  lazy val version = attributes("@version").as[BigInt]
}

case class Result(rowset: eveapi.xml.account.map.Jumps.Rowset, dataTime: String)

case class Rowset(row: Seq[eveapi.xml.account.map.Jumps.Row] = Nil,
                  attributes: Map[String, scalaxb.DataRecord[Any]] = Map()) {
  lazy val columns = attributes("@columns").as[String]
  lazy val key = attributes("@key").as[String]
  lazy val name = attributes("@name").as[String]
}

case class Row(attributes: Map[String, scalaxb.DataRecord[Any]] = Map()) {
  lazy val shipJumps = attributes("@shipJumps").as[BigInt]
  lazy val solarSystemID = attributes("@solarSystemID").as[BigInt]
}
